// 자체 제작 문제 팩을 재현 가능하게 생성한다.
const fs = require('node:fs');
const path = require('node:path');
const hints = require('./hints.cjs');
const column = (name, type, description) => ({name,type,description});
const table = (name,description,columns) => ({name,description,columns:columns.map(x=>column(...x))});
const shop={version:1,id:'shop',title:'작은 상점의 주문 분석',tables:[
 table('customers','고객. customer_id는 고유하며 city는 NULL일 수 있다.',[['customer_id','INT','고객 번호'],['name','VARCHAR(100)','고객 이름'],['city','VARCHAR(100)','거주 도시'],['joined_at','DATE','가입일']]),
 table('products','상품. product_id는 고유하며 가격은 0 이상이다.',[['product_id','INT','상품 번호'],['name','VARCHAR(100)','상품 이름'],['category','VARCHAR(100)','분류'],['price','DECIMAL(12,2)','현재 단가']]),
 table('orders','주문. order_id는 고유. status는 paid 또는 canceled. 고객 참조는 유효하다.',[['order_id','INT','주문 번호'],['customer_id','INT','고객 번호'],['ordered_at','DATE','주문일'],['status','VARCHAR(100)','주문 상태']]),
 table('order_items','주문 상품 행. 같은 주문·상품의 여러 행이 가능하다. 수량은 양수. 주문과 상품 참조는 유효하다.',[['order_id','INT','주문 번호'],['product_id','INT','상품 번호'],['quantity','INT','수량'],['unit_price','DECIMAL(12,2)','구매 당시 단가']])],datasets:[],problems:[]};
shop.datasets=[
{name:'public',rows:{customers:[[1,'가람','서울','2024-01-01'],[2,'나래','부산','2024-01-15'],[3,'다온',null,'2024-02-01'],[4,'라온','서울','2023-12-31'],[5,'마루','대전','2024-03-01'],[6,'바다','부산','2024-01-01']],products:[[1,'노트','문구',1000],[2,'펜','문구',500],[3,'컵','생활',3000],[4,'수건','생활',2000],[5,'책','도서',5000],[6,'지도','도서',5000]],orders:[[1,1,'2024-01-01','paid'],[2,1,'2024-01-02','paid'],[3,2,'2024-01-31','paid'],[4,2,'2024-02-01','canceled'],[5,3,'2024-02-01','paid'],[6,1,'2024-02-01','paid'],[7,4,'2024-02-29','paid'],[8,3,'2024-03-01','paid'],[9,6,'2023-12-31','paid'],[10,1,'2024-01-03','paid'],[11,4,'2024-02-29','paid']],order_items:[[1,1,2,1000],[1,2,1,500],[2,3,1,3000],[3,1,1,1000],[3,1,1,1000],[4,5,2,5000],[5,2,4,500],[6,5,1,5000],[7,3,1,2500],[8,1,1,1000],[8,2,2,500],[9,4,1,2000],[10,4,1,2000],[11,6,1,5000]]}},
{name:'hidden_edges',rows:{customers:[[1,'같은이름','서울','2024-01-31'],[2,'같은이름',null,'2024-02-01'],[3,'미구매','서울','2023-12-01'],[4,'늦가입','제주','2024-02-29'],[5,'취소만','부산','2024-01-01']],products:[[1,'공책','문구',0],[2,'연필','문구',100],[3,'접시','생활',100],[4,'사전','도서',200],[5,'미판매','도서',200]],orders:[[1,1,'2024-01-31','paid'],[2,1,'2024-01-31','paid'],[3,1,'2024-02-01','paid'],[4,1,'2024-02-02','paid'],[5,1,'2024-02-04','paid'],[6,2,'2024-02-01','paid'],[7,2,'2024-03-01','paid'],[8,4,'2024-02-29','paid'],[9,4,'2024-03-01','paid'],[10,4,'2024-03-02','paid'],[11,5,'2024-01-15','canceled'],[12,2,'2024-01-01','canceled'],[13,2,'2024-02-02','paid'],[14,2,'2024-02-02','paid'],[15,2,'2024-02-03','paid'],[16,2,'2024-02-04','paid']],order_items:[[1,1,1,0],[2,2,2,100],[3,3,2,100],[4,4,1,200],[5,4,2,200],[6,2,1,100],[6,2,1,100],[7,3,1,200],[8,1,1,0],[9,2,1,100],[10,3,1,100],[11,5,10,200],[12,1,1,0]]}},
{name:'hidden_sparse',rows:{customers:[[10,'봄',null,'2023-12-31'],[20,'여름','인천','2024-03-01'],[30,'가을','인천','2024-01-01'],[40,'겨울','대구','2024-01-01']],products:[[10,'종이','문구',50],[20,'볼펜','문구',50],[30,'그릇','생활',500],[40,'시집','도서',500]],orders:[[10,10,'2023-12-31','paid'],[20,10,'2024-01-01','paid'],[30,10,'2024-01-02','paid'],[40,30,'2024-01-15','paid'],[50,30,'2024-03-01','paid'],[60,20,'2024-03-01','paid'],[70,40,'2024-01-31','canceled'],[80,30,'2024-02-29','paid'],[90,20,'2024-03-02','paid'],[100,20,'2024-03-03','paid']],order_items:[[10,10,1,50],[20,10,1,50],[20,10,2,50],[30,20,3,50],[40,30,1,500],[50,40,1,500],[60,20,1,50],[70,10,1,50],[80,10,1,50],[80,20,1,50],[90,10,4,50]]}}
];
let ids={1:0,2:0,3:0,4:0,5:0};
function add(pack,level,title,topic,tables,columns,description,solution,explanation){
 const id=`level${level}_${String(++ids[level]).padStart(2,'0')}`;
 pack.problems.push({id,level,title,topic,tables:tables.split(','),columns:columns.split(','),ordered:true,description:description+' 결과 열은 '+columns+' 순서로 출력한다. 별도 범위를 명시하지 않은 날짜 조건은 전체 기간을 대상으로 한다.',solution,explanation,hints:[`핵심 개념: ${topic}. 이 개념을 적용할 열과 결과의 행 단위를 먼저 확인하세요.`,explanation,'-- 주석으로 표시된 빈칸을 채우세요.\n'+hints[level][ids[level]-1]],starter:'-- 조건과 출력 열을 확인한 뒤 쿼리를 작성하세요.\nSELECT '});
}
add(shop,1,'서울 고객 찾기','WHERE','customers','customer_id,name','서울 거주 고객을 고객 번호 오름차순으로 조회한다. 도시가 NULL이면 제외한다.',"SELECT customer_id,name FROM customers WHERE city='서울' ORDER BY customer_id",'문자열 조건은 작은따옴표로 감싼다. NULL은 서울과 같지 않으므로 선택되지 않는다.');
add(shop,1,'가격 범위 안의 상품','BETWEEN','products','product_id,name,price','현재 단가가 1000 이상 3000 이하인 상품을 가격 내림차순, 상품 번호 오름차순으로 조회한다. 두 경계를 모두 포함한다.',"SELECT product_id,name,price FROM products WHERE price BETWEEN 1000 AND 3000 ORDER BY price DESC,product_id",'BETWEEN은 양 끝을 포함한다. 같은 가격의 순서는 상품 번호로 결정한다.');
add(shop,1,'도시를 입력하지 않은 고객','NULL','customers','customer_id,name','거주 도시가 NULL인 고객만 고객 번호 오름차순으로 조회한다. 빈 문자열을 NULL로 취급하지 않는다.',"SELECT customer_id,name FROM customers WHERE city IS NULL ORDER BY customer_id",'NULL은 = NULL이 아니라 IS NULL로 검사한다.');
add(shop,1,'1월 결제 주문','날짜 필터','orders','order_id,customer_id','2024년 1월 1일부터 1월 31일까지 결제 완료(paid)된 주문을 주문 번호 오름차순으로 조회한다.',"SELECT order_id,customer_id FROM orders WHERE status='paid' AND ordered_at>='2024-01-01' AND ordered_at<'2024-02-01' ORDER BY order_id",'다음 달 첫날 미만의 반개방 구간은 월말 일수를 직접 계산할 필요가 없다.');
add(shop,1,'상품 분류 목록','DISTINCT','products','category','등록된 상품 분류를 중복 없이 분류 오름차순으로 조회한다.',"SELECT DISTINCT category FROM products ORDER BY category",'DISTINCT를 적용한 열 조합 단위로 중복이 제거된다.');
add(shop,1,'문구 예상 구매액','산술식','products','product_id,name,total_price','문구 상품을 각각 3개씩 현재 단가로 살 때의 금액 total_price를 계산한다. 상품 번호 오름차순이다.',"SELECT product_id,name,price*3 AS total_price FROM products WHERE category='문구' ORDER BY product_id",'원본 가격을 바꾸지 않고 SELECT 식으로 계산 결과를 만든다.');
add(shop,1,'이름에 노가 들어간 상품','LIKE','products','product_id,name','상품 이름에 글자 노가 한 번 이상 포함되는 상품을 상품 번호 오름차순으로 조회한다.',"SELECT product_id,name FROM products WHERE name LIKE '%노%' ORDER BY product_id",'%는 길이 0 이상인 문자열과 대응한다. 앞뒤 모두 붙여 포함 검색을 수행한다.');
add(shop,2,'분류별 상품 통계','GROUP BY','products','category,product_count,avg_price','분류별 상품 수와 현재 단가 평균을 소수 둘째 자리로 반올림해 조회한다. 분류 오름차순이다.',"SELECT category,COUNT(*) AS product_count,ROUND(AVG(price),2) AS avg_price FROM products GROUP BY category ORDER BY category",'상품 테이블의 한 행이 상품 하나이므로 COUNT(*)가 상품 수다. 반올림은 평균 계산 뒤 적용한다.');
add(shop,2,'주문이 두 건 이상인 고객 번호','HAVING','orders','customer_id,order_count','전체 기간 paid 주문이 2건 이상인 고객 번호와 해당 주문 수를 주문 수 내림차순, 고객 번호 오름차순으로 조회한다.',"SELECT customer_id,COUNT(*) AS order_count FROM orders WHERE status='paid' GROUP BY customer_id HAVING COUNT(*)>=2 ORDER BY order_count DESC,customer_id",'행 필터는 WHERE, 그룹 단위 조건은 HAVING에 둔다.');
add(shop,2,'도시 미입력 묶음','COALESCE','customers','city_label,customer_count','NULL 도시를 미입력으로 표시하고 도시별 고객 수를 조회한다. 실제 도시값에 미입력은 없다. city_label 오름차순이다.',"SELECT COALESCE(city,'미입력') AS city_label,COUNT(*) AS customer_count FROM customers GROUP BY COALESCE(city,'미입력') ORDER BY city_label",'COUNT(city)는 NULL을 세지 않는다. 고객 수는 COUNT(*)로 계산한다.');
add(shop,2,'월별 상태별 주문 수','조건부 집계','orders','month,paid_count,canceled_count','주문이 존재하는 모든 월에 대해 paid와 canceled 주문 수를 각각 집계한다. month는 YYYY-MM이며 오름차순이다. 해당 상태가 없으면 0이다.',"SELECT DATE_FORMAT(ordered_at,'%Y-%m') AS month,SUM(status='paid') AS paid_count,SUM(status='canceled') AS canceled_count FROM orders GROUP BY DATE_FORMAT(ordered_at,'%Y-%m') ORDER BY month",'MySQL 비교식의 참은 1, 거짓은 0이므로 SUM으로 조건별 개수를 셀 수 있다.');
add(shop,2,'상품의 가격 등급','CASE','products','product_id,price_band','현재 단가가 1000 미만이면 저가, 1000 이상 3000 미만이면 중가, 나머지는 고가로 표시한다. 상품 번호 오름차순이다.',"SELECT product_id,CASE WHEN price<1000 THEN '저가' WHEN price<3000 THEN '중가' ELSE '고가' END AS price_band FROM products ORDER BY product_id",'CASE는 첫 번째로 만족한 분기를 선택한다. 앞 조건을 통과하지 못한 범위를 다음 조건이 이어받는다.');
add(shop,2,'월말 가입 고객','날짜 함수','customers','customer_id,joined_at','가입일이 해당 월의 마지막 날짜인 고객을 고객 번호 오름차순으로 조회한다. 윤년의 2월도 실제 달력을 적용한다.',"SELECT customer_id,joined_at FROM customers WHERE joined_at=LAST_DAY(joined_at) ORDER BY customer_id",'LAST_DAY는 월별 일수와 윤년을 처리하므로 날짜 문자열 끝자리 비교가 필요 없다.');
add(shop,2,'주문 상품 행의 합계','중복 집계','order_items','order_id,total_quantity,order_amount','상품 행이 있는 주문별 총수량과 구매 당시 단가 기준 금액 합계를 주문 번호 오름차순으로 조회한다. 중복된 주문·상품 행도 각각 구매량에 포함한다. 주문 상태는 구분하지 않는다.',"SELECT order_id,SUM(quantity) AS total_quantity,SUM(quantity*unit_price) AS order_amount FROM order_items GROUP BY order_id ORDER BY order_id",'SUM(DISTINCT ...)는 값이 같은 서로 다른 구매를 없애므로 사용하면 안 된다.');
add(shop,3,'모든 고객의 결제 주문 수','LEFT JOIN','customers,orders','customer_id,name,paid_count','모든 고객의 paid 주문 수를 조회한다. 주문이 없는 고객도 0으로 포함하고 고객 번호 오름차순으로 정렬한다.',"SELECT c.customer_id,c.name,COUNT(o.order_id) AS paid_count FROM customers c LEFT JOIN orders o ON o.customer_id=c.customer_id AND o.status='paid' GROUP BY c.customer_id,c.name ORDER BY c.customer_id",'상태 조건을 ON에 두어 주문이 없는 고객을 보존한다. COUNT(*) 대신 주문 번호를 센다.');
add(shop,3,'결제 구매 이력이 없는 상품','NOT EXISTS','products,order_items,orders','product_id,name','어떤 paid 주문에도 포함되지 않은 상품을 상품 번호 오름차순으로 조회한다. canceled 주문에만 있는 상품도 포함한다.',"SELECT p.product_id,p.name FROM products p WHERE NOT EXISTS (SELECT 1 FROM order_items i JOIN orders o ON o.order_id=i.order_id WHERE i.product_id=p.product_id AND o.status='paid') ORDER BY p.product_id",'NOT EXISTS는 조건에 맞는 관계가 없는지 확인하며 자식 행 중복의 영향을 받지 않는다.');
add(shop,3,'도시별 결제 매출','다중 JOIN','customers,orders,order_items','city_label,revenue','paid 주문의 상품 행이 있는 도시별 매출을 조회한다. 구매 당시 단가를 사용하며 NULL 도시는 미입력으로 표시한다. 매출 내림차순, city_label 오름차순이다. 실제 도시값에 미입력은 없다.',"SELECT COALESCE(c.city,'미입력') AS city_label,SUM(i.quantity*i.unit_price) AS revenue FROM customers c JOIN orders o ON o.customer_id=c.customer_id JOIN order_items i ON i.order_id=o.order_id WHERE o.status='paid' GROUP BY COALESCE(c.city,'미입력') ORDER BY revenue DESC,city_label",'주문 상품 행의 금액을 합산해야 한다. 현재 상품 가격은 과거 매출에 사용하지 않는다.');
add(shop,3,'분류 평균보다 비싼 상품','상관 서브쿼리','products','product_id,name,price','자신의 분류에 속한 모든 상품의 현재 평균 단가보다 엄격히 비싼 상품을 상품 번호 오름차순으로 조회한다. 평균과 같으면 제외한다.',"SELECT p.product_id,p.name,p.price FROM products p WHERE p.price>(SELECT AVG(q.price) FROM products q WHERE q.category=p.category) ORDER BY p.product_id",'상관 조건으로 분류별 비교 기준을 만든다. 비교 전 평균을 반올림하지 않는다.');
add(shop,3,'문구와 생활을 모두 산 고객','집합 교집합','customers,orders,order_items,products','customer_id,name','전체 기간 paid 주문에서 문구와 생활 분류 상품을 각각 한 번 이상 구매한 고객을 고객 번호 오름차순으로 조회한다. 한 주문에서 모두 살 필요는 없다.',"SELECT c.customer_id,c.name FROM customers c JOIN orders o ON o.customer_id=c.customer_id JOIN order_items i ON i.order_id=o.order_id JOIN products p ON p.product_id=i.product_id WHERE o.status='paid' AND p.category IN ('문구','생활') GROUP BY c.customer_id,c.name HAVING COUNT(DISTINCT p.category)=2 ORDER BY c.customer_id",'대상 두 분류로 제한한 뒤 서로 다른 분류 수를 세면 반복 구매와 무관하게 교집합을 확인할 수 있다.');
add(shop,3,'각 고객의 첫 결제일','집계 서브쿼리','customers,orders','customer_id,name,first_paid_at','모든 고객의 최초 paid 주문일을 조회한다. 결제 이력이 없으면 NULL을 출력하고 고객 번호 오름차순으로 정렬한다.',"SELECT c.customer_id,c.name,MIN(o.ordered_at) AS first_paid_at FROM customers c LEFT JOIN orders o ON o.customer_id=c.customer_id AND o.status='paid' GROUP BY c.customer_id,c.name ORDER BY c.customer_id",'최초 날짜만 필요하면 정렬이나 윈도 함수보다 MIN 집계가 간단하다.');
add(shop,3,'평균 주문액보다 큰 주문','파생 테이블','orders,order_items','order_id,order_amount','전체 paid 주문의 평균 주문액보다 엄격히 큰 paid 주문을 조회한다. 상품 행이 없는 주문액은 0이며 평균 분모에도 포함한다. 주문액 내림차순, 주문 번호 오름차순이다.',"SELECT a.order_id,a.order_amount FROM (SELECT o.order_id,COALESCE(SUM(i.quantity*i.unit_price),0) AS order_amount FROM orders o LEFT JOIN order_items i ON i.order_id=o.order_id WHERE o.status='paid' GROUP BY o.order_id) a WHERE a.order_amount>(SELECT AVG(b.amount) FROM (SELECT o.order_id,COALESCE(SUM(i.quantity*i.unit_price),0) AS amount FROM orders o LEFT JOIN order_items i ON i.order_id=o.order_id WHERE o.status='paid' GROUP BY o.order_id) b) ORDER BY a.order_amount DESC,a.order_id",'상품 행 평균은 주문액 평균과 다르다. 먼저 주문 단위 금액을 만든 다음 평균을 구한다.');
add(shop,4,'고객별 결제 순번','ROW_NUMBER','orders','customer_id,order_id,purchase_number','paid 주문에 고객별 구매 순번을 1부터 매긴다. 같은 주문일에는 주문 번호가 작은 주문이 먼저다. 고객 번호, 구매 순번 오름차순이다.',"SELECT customer_id,order_id,ROW_NUMBER() OVER(PARTITION BY customer_id ORDER BY ordered_at,order_id) AS purchase_number FROM orders WHERE status='paid' ORDER BY customer_id,purchase_number",'ROW_NUMBER의 정렬에 고유 주문 번호를 추가하면 같은 날짜에서도 순번이 안정적이다.');
add(shop,4,'분류별 가격 상위 두 순위','DENSE_RANK','products','category,product_id,price,price_rank','분류별 서로 다른 현재 가격 중 상위 두 가격에 속하는 모든 상품을 조회한다. 동점은 모두 같은 순위이며 다음 순위는 건너뛰지 않는다. 분류, 순위, 상품 번호 오름차순이다.',"WITH ranked AS (SELECT category,product_id,price,DENSE_RANK() OVER(PARTITION BY category ORDER BY price DESC) AS price_rank FROM products) SELECT category,product_id,price,price_rank FROM ranked WHERE price_rank<=2 ORDER BY category,price_rank,product_id",'동점 모두 포함한 서로 다른 가격 두 개는 DENSE_RANK로 선택한다. ROW_NUMBER는 동점을 잘라낸다.');
add(shop,4,'고객별 직전 결제 간격','LAG','orders','customer_id,order_id,gap_days','paid 주문별 직전 paid 주문과의 날짜 차이를 구한다. 고객별 주문일, 주문 번호 순으로 직전을 정하며 첫 주문은 NULL이다. 같은 날의 간격은 0이다. 고객 번호, 주문일, 주문 번호 순으로 출력한다.',"SELECT customer_id,order_id,DATEDIFF(ordered_at,LAG(ordered_at) OVER(PARTITION BY customer_id ORDER BY ordered_at,order_id)) AS gap_days FROM orders WHERE status='paid' ORDER BY customer_id,ordered_at,order_id",'LAG로 이전 행의 날짜를 가져온다. 고객별 파티션이 없으면 다른 고객 주문과 비교하게 된다.');
add(shop,4,'일별 누적 매출','누적 SUM','orders,order_items','sale_date,revenue,cumulative_revenue','paid 주문이 있는 날짜별 매출과 그 날짜까지의 누적 매출을 날짜 오름차순으로 조회한다. 상품 행이 없는 주문은 0이며 paid 주문이 없는 날짜는 출력하지 않는다.',"WITH daily AS (SELECT o.ordered_at AS sale_date,COALESCE(SUM(i.quantity*i.unit_price),0) AS revenue FROM orders o LEFT JOIN order_items i ON i.order_id=o.order_id WHERE o.status='paid' GROUP BY o.ordered_at) SELECT sale_date,revenue,SUM(revenue) OVER(ORDER BY sale_date ROWS UNBOUNDED PRECEDING) AS cumulative_revenue FROM daily ORDER BY sale_date",'먼저 날짜별 집계로 같은 날을 합친 뒤 누적한다. ROWS 프레임을 명시해 누적 범위를 분명히 한다.');
add(shop,4,'고객 매출 비중','전체 윈도 합계','customers,orders,order_items','customer_id,revenue,revenue_pct','모든 고객의 paid 매출과 전체 paid 매출 대비 백분율을 소수 둘째 자리로 반올림해 조회한다. 미구매는 매출 0이며 전체 매출이 0이면 비율도 0이다. 고객 번호 오름차순이다.',"WITH totals AS (SELECT c.customer_id,COALESCE(SUM(i.quantity*i.unit_price),0) AS revenue FROM customers c LEFT JOIN orders o ON o.customer_id=c.customer_id AND o.status='paid' LEFT JOIN order_items i ON i.order_id=o.order_id GROUP BY c.customer_id) SELECT customer_id,revenue,COALESCE(ROUND(100.0*revenue/NULLIF(SUM(revenue) OVER(),0),2),0) AS revenue_pct FROM totals ORDER BY customer_id",'고객별 합계 위에 전체 윈도 합계를 적용한다. NULLIF로 0 나눗셈을 피한 후 COALESCE로 정책을 구현한다.');
add(shop,4,'가입 후 30일 안의 결제','다단계 CTE','customers,orders,order_items','customer_id,revenue_30d','모든 고객에 대해 가입일부터 30일간의 paid 매출을 조회한다. 가입일 포함, 가입일+30일 제외이며 가입 전 주문은 제외한다. 매출이 없으면 0, 고객 번호 오름차순이다.',"WITH eligible AS (SELECT c.customer_id,o.order_id FROM customers c LEFT JOIN orders o ON o.customer_id=c.customer_id AND o.status='paid' AND o.ordered_at>=c.joined_at AND o.ordered_at<DATE_ADD(c.joined_at,INTERVAL 30 DAY)) SELECT e.customer_id,COALESCE(SUM(i.quantity*i.unit_price),0) AS revenue_30d FROM eligible e LEFT JOIN order_items i ON i.order_id=e.order_id GROUP BY e.customer_id ORDER BY e.customer_id",'가입일 기준의 개별 구간을 조인 조건으로 구성해야 미구매 고객도 남는다. 30일은 달력 한 달과 다르다.');
add(shop,4,'주문 두 건의 이동 평균','이동 윈도','orders,order_items','customer_id,order_id,moving_avg','paid 주문을 고객별 주문일, 주문 번호 순으로 나열하여 현재 주문과 직전 주문의 주문액 평균을 소수 둘째 자리로 반올림한다. 첫 주문은 자신만 평균낸다. 상품 행이 없으면 주문액 0. 고객 번호, 주문일, 주문 번호 순이다.',"WITH amounts AS (SELECT o.customer_id,o.order_id,o.ordered_at,COALESCE(SUM(i.quantity*i.unit_price),0) AS amount FROM orders o LEFT JOIN order_items i ON i.order_id=o.order_id WHERE o.status='paid' GROUP BY o.customer_id,o.order_id,o.ordered_at) SELECT customer_id,order_id,ROUND(AVG(amount) OVER(PARTITION BY customer_id ORDER BY ordered_at,order_id ROWS BETWEEN 1 PRECEDING AND CURRENT ROW),2) AS moving_avg FROM amounts ORDER BY customer_id,ordered_at,order_id",'최근 두 주문은 최근 이틀과 다르다. ROWS 1 PRECEDING으로 행 기준 창을 만든다.');
add(shop,5,'가입 코호트의 다음 달 결제율','코호트','customers,orders','cohort_month,customer_count,retained_count,retention_pct','가입 월별 전체 고객 수와 가입 월 바로 다음 달에 paid 주문을 한 고객 수, 그 비율(백분율, 소수 둘째 자리)을 조회한다. 같은 고객의 여러 주문은 한 번만 센다. 다음 달은 달력 월 기준이며 코호트 월 오름차순이다.',"WITH cohort AS (SELECT customer_id,DATE_FORMAT(joined_at,'%Y-%m') AS cohort_month,CAST(DATE_FORMAT(joined_at,'%Y-%m-01') AS DATE) AS month_start FROM customers), flags AS (SELECT c.customer_id,c.cohort_month,EXISTS(SELECT 1 FROM orders o WHERE o.customer_id=c.customer_id AND o.status='paid' AND o.ordered_at>=DATE_ADD(c.month_start,INTERVAL 1 MONTH) AND o.ordered_at<DATE_ADD(c.month_start,INTERVAL 2 MONTH)) AS retained FROM cohort c) SELECT cohort_month,COUNT(*) AS customer_count,SUM(retained) AS retained_count,ROUND(100.0*SUM(retained)/COUNT(*),2) AS retention_pct FROM flags GROUP BY cohort_month ORDER BY cohort_month",'분모는 결제자가 아니라 해당 가입 월의 전체 고객이다. EXISTS로 반복 주문에 의한 분자 중복을 막는다.');
add(shop,5,'3일 이상 연속 결제 구간','연속 구간','orders','customer_id,start_date,end_date,day_count','같은 고객이 매일 한 번 이상 paid 주문한 최대 연속 날짜 구간 중 길이가 3일 이상인 구간을 모두 조회한다. 같은 날 여러 주문은 하루로 센다. 고객 번호, 시작일 오름차순이다.',"WITH days AS (SELECT DISTINCT customer_id,ordered_at FROM orders WHERE status='paid'), numbered AS (SELECT customer_id,ordered_at,ROW_NUMBER() OVER(PARTITION BY customer_id ORDER BY ordered_at) AS rn FROM days), islands AS (SELECT customer_id,ordered_at,DATE_SUB(ordered_at,INTERVAL rn DAY) AS grp FROM numbered) SELECT customer_id,MIN(ordered_at) AS start_date,MAX(ordered_at) AS end_date,COUNT(*) AS day_count FROM islands GROUP BY customer_id,grp HAVING COUNT(*)>=3 ORDER BY customer_id,start_date",'날짜 중복을 먼저 없앤다. 연속 날짜에서 날짜-순번은 일정하므로 같은 최대 구간으로 묶인다.');
add(shop,5,'문구 전 상품 구매자','관계 나눗셈','customers,products,orders,order_items','customer_id,name','현재 등록된 모든 문구 상품을 전체 기간 paid 주문에서 각각 한 번 이상 구매한 고객을 조회한다. 문구 상품이 하나도 없다면 모든 고객이 조건을 만족한다. 고객 번호 오름차순이다.',"SELECT c.customer_id,c.name FROM customers c WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.category='문구' AND NOT EXISTS (SELECT 1 FROM orders o JOIN order_items i ON i.order_id=o.order_id WHERE o.customer_id=c.customer_id AND o.status='paid' AND i.product_id=p.product_id)) ORDER BY c.customer_id",'구매하지 않은 필수 상품이 하나도 없다는 이중 NOT EXISTS가 모든 조건을 표현한다. 빈 필수 집합도 자연스럽게 처리한다.');
add(shop,5,'빈 날짜를 포함한 7일 매출','재귀 CTE와 이동 합계','orders,order_items','sale_date,revenue_7d','2024년 1월 1일부터 1월 7일까지 매일 한 행씩 출력한다. revenue_7d는 해당 날짜와 직전 6일의 paid 매출 합계다. 출력 시작일 이전 주문도 창에 들어오면 포함한다. 주문 없는 날 매출은 0. 날짜 오름차순이다.',"WITH RECURSIVE dates AS (SELECT CAST('2023-12-26' AS DATE) AS d UNION ALL SELECT DATE_ADD(d,INTERVAL 1 DAY) FROM dates WHERE d<'2024-01-07'), daily AS (SELECT o.ordered_at, SUM(i.quantity*i.unit_price) AS revenue FROM orders o JOIN order_items i ON i.order_id=o.order_id WHERE o.status='paid' AND o.ordered_at>='2023-12-26' AND o.ordered_at<='2024-01-07' GROUP BY o.ordered_at), rolling AS (SELECT d,SUM(COALESCE(revenue,0)) OVER(ORDER BY d ROWS BETWEEN 6 PRECEDING AND CURRENT ROW) AS revenue_7d FROM dates LEFT JOIN daily ON ordered_at=d) SELECT d AS sale_date,revenue_7d FROM rolling WHERE d>='2024-01-01' ORDER BY sale_date",'빈 날짜를 채우고 출력 시작일 이전 여섯 날짜까지 창을 계산한 다음 출력 범위를 자른다.');
add(shop,5,'두 번째 결제까지 걸린 날짜','첫 두 이벤트','customers,orders','customer_id,days_to_second','모든 고객에 대해 첫 번째 paid 주문부터 두 번째 paid 주문까지의 날짜 차이를 출력한다. 주문일, 주문 번호로 순서를 정하며 같은 날 주문 둘은 0일이다. paid 주문이 2건 미만이면 NULL. 고객 번호 오름차순이다.',"WITH ranked AS (SELECT customer_id,ordered_at,ROW_NUMBER() OVER(PARTITION BY customer_id ORDER BY ordered_at,order_id) AS rn FROM orders WHERE status='paid'), first_two AS (SELECT customer_id,DATEDIFF(MAX(CASE WHEN rn=2 THEN ordered_at END),MAX(CASE WHEN rn=1 THEN ordered_at END)) AS days_to_second FROM ranked WHERE rn<=2 GROUP BY customer_id) SELECT c.customer_id,f.days_to_second FROM customers c LEFT JOIN first_two f ON f.customer_id=c.customer_id ORDER BY c.customer_id",'서로 다른 두 날짜가 아니라 두 주문을 순위로 정한다. 두 번째 주문이 없으면 날짜 차이도 NULL이다.');
add(shop,5,'월별 고객 매출 중앙값','중앙값','orders,order_items','month,median_revenue','각 월에 paid 주문을 한 고객별 월 매출을 먼저 계산하고, 그 값들의 중앙값을 소수 둘째 자리로 출력한다. 상품 없는 주문도 매출 0으로 포함하나 그달 미구매 고객은 제외한다. 짝수 개이면 가운데 두 값의 평균. 월 YYYY-MM 오름차순이다.',"WITH totals AS (SELECT DATE_FORMAT(o.ordered_at,'%Y-%m') AS month,o.customer_id,COALESCE(SUM(i.quantity*i.unit_price),0) AS revenue FROM orders o LEFT JOIN order_items i ON i.order_id=o.order_id WHERE o.status='paid' GROUP BY DATE_FORMAT(o.ordered_at,'%Y-%m'),o.customer_id), ranked AS (SELECT month,revenue,ROW_NUMBER() OVER(PARTITION BY month ORDER BY revenue,customer_id) AS rn,COUNT(*) OVER(PARTITION BY month) AS n FROM totals) SELECT month,ROUND(AVG(revenue),2) AS median_revenue FROM ranked WHERE rn IN (FLOOR((n+1)/2),FLOOR((n+2)/2)) GROUP BY month ORDER BY month",'월별 고객 단위로 집계한 뒤 가운데 위치를 선택한다. 홀수 개이면 두 위치 식이 같은 값을 가리킨다.');
add(shop,5,'동시 구매 상품 쌍','자기 조인과 중복 제거','orders,order_items','product_a,product_b,order_count','같은 paid 주문에서 함께 등장한 서로 다른 상품 쌍별 주문 수를 조회한다. 상품 번호가 작은 쪽이 product_a이다. 같은 주문의 중복 상품 행과 수량은 횟수를 늘리지 않는다. 주문 수 내림차순, product_a, product_b 오름차순이다.',"WITH unique_items AS (SELECT DISTINCT i.order_id,i.product_id FROM order_items i JOIN orders o ON o.order_id=i.order_id WHERE o.status='paid') SELECT a.product_id AS product_a,b.product_id AS product_b,COUNT(*) AS order_count FROM unique_items a JOIN unique_items b ON a.order_id=b.order_id AND a.product_id<b.product_id GROUP BY a.product_id,b.product_id ORDER BY order_count DESC,product_a,product_b",'주문·상품을 먼저 유일하게 만들고 작은 번호에서 큰 번호로만 조인하여 행 중복과 역순 쌍을 함께 방지한다.');
const academy={version:1,id:'academy',title:'학습 서비스의 활동 분석',tables:[
 table('members','회원. member_id는 고유. region은 NULL일 수 있다.',[['member_id','INT','회원 번호'],['name','VARCHAR(100)','이름'],['region','VARCHAR(100)','지역'],['joined_at','DATE','가입일']]),
 table('courses','강좌. course_id는 고유. required는 필수 강좌이면 1, 선택이면 0.',[['course_id','INT','강좌 번호'],['title','VARCHAR(100)','강좌 이름'],['track','VARCHAR(100)','학습 분야'],['required','INT','필수 여부']]),
 table('enrollments','수강 등록. enrollment_id는 고유. 같은 회원·강좌 재등록 가능. completed_at은 미완료이면 NULL이며 완료는 등록일 이후이다.',[['enrollment_id','INT','등록 번호'],['member_id','INT','회원 번호'],['course_id','INT','강좌 번호'],['enrolled_at','DATE','등록일'],['completed_at','DATE','완료일']]),
 table('attempts','응시. attempt_id는 고유. score는 0~100 정수 또는 미채점 NULL. 회원·강좌 참조는 유효하며 수강 등록 없이 응시할 수 있다.',[['attempt_id','INT','응시 번호'],['member_id','INT','회원 번호'],['course_id','INT','강좌 번호'],['attempted_at','DATE','응시일'],['score','INT','점수']]),
 table('activity','활동 기록. activity_id는 고유. kind는 login 또는 study. duration은 0 이상인 분 단위 정수. 같은 날짜에 여러 기록이 가능하다.',[['activity_id','INT','활동 번호'],['member_id','INT','회원 번호'],['activity_date','DATE','활동일'],['kind','VARCHAR(100)','활동 종류'],['duration','INT','활동 시간(분)']])],datasets:[],problems:[]};
academy.datasets=[
{name:'public',rows:{members:[[1,'가영','서울','2024-01-01'],[2,'나윤','부산','2024-01-15'],[3,'다희',null,'2024-02-01'],[4,'라희','서울','2023-12-31'],[5,'마음','대전','2024-03-01']],courses:[[1,'SQL 입문','데이터',1],[2,'통계 기초','데이터',1],[3,'글쓰기','교양',0],[4,'논리학','교양',0]],enrollments:[[1,1,1,'2024-01-01','2024-01-10'],[2,1,2,'2024-01-05','2024-01-20'],[3,2,1,'2024-01-15',null],[4,3,1,'2024-02-01','2024-02-29'],[5,4,3,'2024-01-01','2024-01-01'],[6,1,1,'2024-02-01',null],[7,2,3,'2024-01-16','2024-02-01']],attempts:[[1,1,1,'2024-01-02',50],[2,1,1,'2024-01-10',80],[3,1,2,'2024-01-20',90],[4,2,1,'2024-01-16',80],[5,2,1,'2024-02-01',null],[6,3,1,'2024-02-29',100],[7,4,3,'2024-01-01',70],[8,2,3,'2024-02-01',70],[9,1,1,'2024-02-01',60],[10,3,2,'2024-03-01',90]],activity:[[1,1,'2024-01-01','login',0],[2,1,'2024-01-01','study',30],[3,1,'2024-01-02','study',20],[4,1,'2024-01-03','study',40],[5,1,'2024-01-05','study',10],[6,2,'2024-01-15','login',0],[7,2,'2024-01-16','study',30],[8,3,'2024-02-01','study',60],[9,3,'2024-02-02','study',20],[10,3,'2024-02-03','study',10],[11,4,'2023-12-31','login',0],[12,4,'2024-01-01','study',30],[13,1,'2024-02-01','login',0],[14,2,'2024-02-01','study',30],[15,3,'2024-03-01','login',0]]}},
{name:'hidden_ties',rows:{members:[[1,'동명이인','제주','2024-01-31'],[2,'동명이인',null,'2024-02-01'],[3,'활동없음','서울','2024-01-01'],[4,'반복학습','서울','2024-02-29']],courses:[[1,'SQL 심화','데이터',1],[2,'분석','데이터',1],[3,'역사','교양',0],[4,'철학','교양',1],[5,'미응시','언어',0]],enrollments:[[1,1,1,'2024-01-31','2024-02-01'],[2,1,1,'2024-02-01','2024-02-02'],[3,1,2,'2024-02-01','2024-02-29'],[4,2,1,'2024-02-01',null],[5,4,1,'2024-02-29','2024-03-01'],[6,4,2,'2024-02-29','2024-03-01'],[7,4,4,'2024-02-29','2024-03-02'],[8,2,3,'2024-02-01',null],[9,2,2,'2024-02-02',null]],attempts:[[1,1,1,'2024-01-31',100],[2,1,1,'2024-01-31',20],[3,1,1,'2024-02-01',80],[4,2,1,'2024-02-01',80],[5,4,1,'2024-02-29',80],[6,1,2,'2024-02-01',null],[7,2,2,'2024-02-01',null],[8,4,2,'2024-03-01',0],[9,4,4,'2024-03-02',100],[10,1,3,'2024-02-02',50],[11,2,3,'2024-02-02',50],[12,4,3,'2024-03-02',100]],activity:[[1,1,'2024-01-31','study',5],[2,1,'2024-01-31','study',5],[3,1,'2024-02-01','study',10],[4,1,'2024-02-02','login',0],[5,1,'2024-02-03','study',20],[6,1,'2024-02-04','study',10],[7,1,'2024-02-05','study',10],[8,2,'2024-02-01','login',0],[9,2,'2024-02-02','login',0],[10,2,'2024-02-03','login',0],[11,4,'2024-02-29','study',0],[12,4,'2024-03-01','study',30],[13,4,'2024-03-02','study',30],[14,1,'2024-02-06','study',10],[15,2,'2024-03-01','study',60]]}},
{name:'hidden_sparse',rows:{members:[[10,'하나',null,'2023-12-31'],[20,'둘','광주','2024-01-01'],[30,'셋','광주','2024-03-01'],[40,'넷','울산','2024-01-01']],courses:[[10,'SQL 첫걸음','데이터',0],[20,'수학','데이터',0],[30,'그림','교양',0]],enrollments:[[10,10,10,'2023-12-31',null],[20,20,20,'2024-01-01','2024-01-31'],[30,20,20,'2024-02-01',null],[40,40,30,'2024-01-01','2024-01-02']],attempts:[[10,10,10,'2023-12-31',null],[20,20,20,'2024-01-01',0],[30,20,20,'2024-01-02',100],[40,40,20,'2024-01-02',50],[50,40,30,'2024-01-02',70],[60,20,20,'2024-02-01',50]],activity:[[10,10,'2023-12-31','study',10],[20,10,'2024-01-01','study',20],[30,10,'2024-01-02','study',30],[40,20,'2024-01-01','study',30],[50,20,'2024-01-01','study',30],[60,20,'2024-01-03','study',60],[70,40,'2024-01-02','login',0],[80,20,'2024-03-01','study',30]]}}
];
add(academy,1,'필수 강좌 목록','기초 조회','courses','course_id,title','필수 여부가 1인 강좌를 강좌 번호 오름차순으로 조회한다.',"SELECT course_id,title FROM courses WHERE required=1 ORDER BY course_id",'정수 형태의 여부 열은 조건에 해당하는 값으로 직접 필터링한다.');
add(academy,1,'미완료 수강 등록','NULL 필터','enrollments','enrollment_id,member_id,course_id','완료일이 NULL인 수강 등록을 등록 번호 오름차순으로 조회한다. 같은 회원·강좌 재등록도 별도 행이다.',"SELECT enrollment_id,member_id,course_id FROM enrollments WHERE completed_at IS NULL ORDER BY enrollment_id",'등록 행 단위 조회이므로 DISTINCT를 사용하면 안 된다.');
add(academy,1,'고득점 응시 정렬','다중 정렬','attempts','attempt_id,member_id,score','점수가 80 이상인 응시를 점수 내림차순, 응시 번호 오름차순으로 조회한다. 미채점 응시는 제외한다.',"SELECT attempt_id,member_id,score FROM attempts WHERE score>=80 ORDER BY score DESC,attempt_id",'점수 동점에도 응시 번호를 정렬 기준으로 추가하여 결과 순서를 확정한다.');
add(academy,1,'두 지역의 회원','IN','members','member_id,name','서울 또는 부산 거주 회원을 회원 번호 오름차순으로 조회한다. NULL 지역은 제외한다.',"SELECT member_id,name FROM members WHERE region IN ('서울','부산') ORDER BY member_id",'동일 열의 여러 후보값 비교는 IN으로 간결하게 표현한다.');
add(academy,1,'학습 시간을 초로 변환','단위 변환','activity','activity_id,duration_seconds','study 기록의 분 단위 시간을 초 단위 duration_seconds로 변환한다. 시간이 0인 기록도 포함하며 활동 번호 오름차순이다.',"SELECT activity_id,duration*60 AS duration_seconds FROM activity WHERE kind='study' ORDER BY activity_id",'단위를 변환할 때 출력 열 이름에도 단위를 드러내면 후속 계산의 혼동을 줄인다.');
add(academy,1,'가장 이른 수강 등록 세 건','LIMIT','enrollments','enrollment_id,enrolled_at','등록일이 가장 빠른 수강 등록을 최대 3건 조회한다. 같은 등록일에는 등록 번호가 작은 것이 먼저다. 전체 행이 3건 미만이면 모두 출력한다.',"SELECT enrollment_id,enrolled_at FROM enrollments ORDER BY enrolled_at,enrollment_id LIMIT 3",'LIMIT 전에 ORDER BY로 선택 기준을 고정한다. 동점 전체 포함이 아니라 정확히 최대 세 행이다.');
add(academy,1,'SQL로 시작하는 강좌','접두어 검색','courses','course_id,title','이름이 영문 SQL로 시작하는 강좌를 강좌 번호 오름차순으로 조회한다. 데이터의 영문 표기는 대문자로 통일되어 있다.',"SELECT course_id,title FROM courses WHERE title LIKE 'SQL%' ORDER BY course_id",'끝에만 %를 붙이면 접두어 검색이 된다.');
add(academy,2,'강좌별 채점 현황','NULL 집계','attempts','course_id,attempt_count,graded_count,avg_score','응시가 있는 강좌별 전체 응시 수, 채점된 응시 수, 채점된 점수 평균(소수 둘째 자리)을 조회한다. 전부 미채점이면 평균 NULL. 강좌 번호 오름차순이다.',"SELECT course_id,COUNT(*) AS attempt_count,COUNT(score) AS graded_count,ROUND(AVG(score),2) AS avg_score FROM attempts GROUP BY course_id ORDER BY course_id",'COUNT(*)는 전체 행, COUNT(score)와 AVG(score)는 NULL이 아닌 값만 계산한다.');
add(academy,2,'일별 학습 시간','SUM','activity','activity_date,total_minutes','study 기록이 있는 날짜별 학습 시간 합계를 날짜 오름차순으로 조회한다. login 시간은 제외하고 0분 study 날짜는 포함한다.',"SELECT activity_date,SUM(duration) AS total_minutes FROM activity WHERE kind='study' GROUP BY activity_date ORDER BY activity_date",'행을 날짜로 묶기 전에 활동 종류를 제한한다.');
add(academy,2,'재응시 회원과 강좌','복합 GROUP BY','attempts','member_id,course_id,attempt_count','채점 여부와 무관하게 같은 강좌에 2회 이상 응시한 회원·강좌 조합과 응시 수를 조회한다. 회원 번호, 강좌 번호 오름차순이다.',"SELECT member_id,course_id,COUNT(*) AS attempt_count FROM attempts GROUP BY member_id,course_id HAVING COUNT(*)>=2 ORDER BY member_id,course_id",'회원 번호만 묶으면 서로 다른 강좌의 응시가 합쳐진다. 분석 단위 두 열을 모두 GROUP BY에 둔다.');
add(academy,2,'완료까지 걸린 날짜','DATEDIFF','enrollments','enrollment_id,completion_days','완료된 수강 등록에 대해 완료일-등록일의 날짜 차이를 조회한다. 당일 완료는 0일이며 등록 번호 오름차순이다.',"SELECT enrollment_id,DATEDIFF(completed_at,enrolled_at) AS completion_days FROM enrollments WHERE completed_at IS NOT NULL ORDER BY enrollment_id",'DATEDIFF의 첫 인수에서 두 번째 인수를 뺀다. 날짜 차이에는 시작일을 추가로 1일 세지 않는다.');
add(academy,2,'회원별 활동 날짜 수','COUNT DISTINCT','activity','member_id,active_days','활동 기록이 있는 회원마다 login과 study를 모두 포함하여 서로 다른 활동 날짜 수를 조회한다. 같은 날의 여러 기록은 하루다. 회원 번호 오름차순이다.',"SELECT member_id,COUNT(DISTINCT activity_date) AS active_days FROM activity GROUP BY member_id ORDER BY member_id",'활동 행 수와 활동 날짜 수는 다르므로 날짜에 DISTINCT를 적용한다.');
add(academy,2,'점수 구간별 응시 수','CASE 집계','attempts','score_band,attempt_count','점수 80 이상은 우수, 60 이상 80 미만은 보통, 60 미만은 보완, NULL은 미채점으로 분류하고 구간별 응시 수를 조회한다. 존재하는 구간만 출력하며 score_band 오름차순이다.',"SELECT CASE WHEN score IS NULL THEN '미채점' WHEN score>=80 THEN '우수' WHEN score>=60 THEN '보통' ELSE '보완' END AS score_band,COUNT(*) AS attempt_count FROM attempts GROUP BY score_band ORDER BY score_band",'NULL 분기를 먼저 명시해야 미채점이 낮은 점수 구간으로 떨어지지 않는다.');
add(academy,2,'회원별 학습 목표 달성','HAVING 합계','activity','member_id,total_minutes','전체 기간 study 시간이 합계 60분 이상인 회원과 학습 시간 합계를 조회한다. 총시간 내림차순, 회원 번호 오름차순이다.',"SELECT member_id,SUM(duration) AS total_minutes FROM activity WHERE kind='study' GROUP BY member_id HAVING SUM(duration)>=60 ORDER BY total_minutes DESC,member_id",'한 기록의 60분 조건이 아니라 회원 전체 합계의 60분 조건이므로 HAVING을 사용한다.');
add(academy,3,'모든 강좌의 등록자 수','LEFT JOIN DISTINCT','courses,enrollments','course_id,title,member_count','모든 강좌에 대해 한 번 이상 등록한 서로 다른 회원 수를 조회한다. 재등록은 중복 계산하지 않고 등록자가 없으면 0이다. 강좌 번호 오름차순이다.',"SELECT c.course_id,c.title,COUNT(DISTINCT e.member_id) AS member_count FROM courses c LEFT JOIN enrollments e ON e.course_id=c.course_id GROUP BY c.course_id,c.title ORDER BY c.course_id",'등록 행 수 대신 회원의 고유 수를 센다. LEFT JOIN은 등록 없는 강좌도 보존한다.');
add(academy,3,'한 번도 채점받지 못한 회원','NOT EXISTS','members,attempts','member_id,name','점수가 NULL이 아닌 응시가 전혀 없는 회원을 조회한다. 응시가 아예 없는 회원과 미채점 응시만 있는 회원 모두 포함한다. 회원 번호 오름차순이다.',"SELECT m.member_id,m.name FROM members m WHERE NOT EXISTS(SELECT 1 FROM attempts a WHERE a.member_id=m.member_id AND a.score IS NOT NULL) ORDER BY m.member_id",'미채점 응시의 존재가 아니라 채점된 응시의 부재를 검사해야 한다.');
add(academy,3,'강좌 평균을 넘은 응시','상관 평균','attempts','attempt_id,course_id,score','자신의 강좌에 속한 모든 채점된 응시의 평균보다 엄격히 높은 점수의 응시를 조회한다. 회원별 최고점으로 바꾸지 않는다. 응시 번호 오름차순이다.',"SELECT a.attempt_id,a.course_id,a.score FROM attempts a WHERE a.score>(SELECT AVG(b.score) FROM attempts b WHERE b.course_id=a.course_id) ORDER BY a.attempt_id",'평균 계산 단위는 모든 응시 행이다. AVG는 미채점 NULL을 제외한다.');
add(academy,3,'분야별 수강 완료자 수','다중 조인','courses,enrollments','track,completed_members','완료된 등록이 하나 이상 있는 분야별로, 해당 분야에서 강좌를 하나 이상 완료한 서로 다른 회원 수를 조회한다. 같은 회원의 여러 완료는 한 번만 센다. 분야 오름차순이다.',"SELECT c.track,COUNT(DISTINCT e.member_id) AS completed_members FROM courses c JOIN enrollments e ON e.course_id=c.course_id WHERE e.completed_at IS NOT NULL GROUP BY c.track ORDER BY c.track",'강좌별로 먼저 회원 수를 더하면 여러 강좌 완료자가 중복된다. 분야 그룹 안에서 직접 DISTINCT한다.');
add(academy,3,'수강 등록 없는 응시','반대 조인','attempts,enrollments','attempt_id,member_id,course_id','응시일 당일까지 해당 회원·강좌의 수강 등록이 없던 응시를 조회한다. 응시일과 같은 날의 등록은 유효하다. 이후 등록은 과거 응시를 유효하게 만들지 않는다. 응시 번호 오름차순이다.',"SELECT a.attempt_id,a.member_id,a.course_id FROM attempts a WHERE NOT EXISTS(SELECT 1 FROM enrollments e WHERE e.member_id=a.member_id AND e.course_id=a.course_id AND e.enrolled_at<=a.attempted_at) ORDER BY a.attempt_id",'관계 유무뿐 아니라 응시 시점까지 존재했는지 시간 조건도 함께 검사한다.');
add(academy,3,'회원별 최고점 평균','두 단계 집계','members,attempts','member_id,avg_best_score','모든 회원에 대해 강좌별 최고 채점 점수를 먼저 구한 뒤 그 최고점들의 평균을 소수 둘째 자리로 조회한다. 채점 점수가 전혀 없는 회원은 NULL이다. 회원 번호 오름차순이다.',"SELECT m.member_id,ROUND(AVG(b.best_score),2) AS avg_best_score FROM members m LEFT JOIN (SELECT member_id,course_id,MAX(score) AS best_score FROM attempts WHERE score IS NOT NULL GROUP BY member_id,course_id) b ON b.member_id=m.member_id GROUP BY m.member_id ORDER BY m.member_id",'응시가 많은 강좌에 가중치가 쏠리지 않도록 먼저 회원·강좌 최고점으로 압축한다.');
add(academy,3,'가입 당일 학습한 회원','EXISTS','members,activity','member_id,name','가입일과 같은 날짜에 study 기록이 한 건 이상 있는 회원을 조회한다. 0분 study도 인정하며 login만 있는 회원은 제외한다. 회원 번호 오름차순이다.',"SELECT m.member_id,m.name FROM members m WHERE EXISTS(SELECT 1 FROM activity a WHERE a.member_id=m.member_id AND a.activity_date=m.joined_at AND a.kind='study') ORDER BY m.member_id",'EXISTS는 여러 당일 기록이 있더라도 회원당 한 행을 유지한다.');
add(academy,4,'강좌별 최고점 공동 순위','RANK','attempts','course_id,member_id,best_score,score_rank','채점된 응시가 있는 회원·강좌별 최고점을 구해 강좌 안에서 높은 점수 순으로 경쟁 순위를 매긴다. 동점은 같은 순위이며 다음 순위는 동점 인원만큼 건너뛴다. 강좌, 순위, 회원 번호 오름차순이다.',"WITH best AS (SELECT course_id,member_id,MAX(score) AS best_score FROM attempts WHERE score IS NOT NULL GROUP BY course_id,member_id) SELECT course_id,member_id,best_score,RANK() OVER(PARTITION BY course_id ORDER BY best_score DESC) AS score_rank FROM best ORDER BY course_id,score_rank,member_id",'최고점을 먼저 집계해야 동일 회원이 순위를 여러 개 차지하지 않는다. 경쟁 순위는 RANK다.');
add(academy,4,'최근 응시 한 건','ROW_NUMBER 최신값','attempts','member_id,course_id,attempt_id,score','응시가 있는 각 회원·강좌의 가장 최근 응시 한 건을 조회한다. 응시일이 같으면 응시 번호가 큰 것이 최근이다. 미채점 응시도 최신 후보에 포함한다. 회원, 강좌 번호 오름차순이다.',"WITH ranked AS (SELECT member_id,course_id,attempt_id,score,ROW_NUMBER() OVER(PARTITION BY member_id,course_id ORDER BY attempted_at DESC,attempt_id DESC) AS rn FROM attempts) SELECT member_id,course_id,attempt_id,score FROM ranked WHERE rn=1 ORDER BY member_id,course_id",'MAX(score)는 최근 점수를 뜻하지 않는다. 날짜와 고유 번호를 기준으로 최신 행 전체를 선택한다.');
add(academy,4,'직전 채점 대비 점수 변화','LAG 필터 순서','attempts','attempt_id,member_id,course_id,score_change','채점된 응시만 대상으로 같은 회원·강좌의 직전 채점 점수 대비 변화량을 구한다. 응시일, 응시 번호 순이며 첫 채점은 NULL이다. 회원, 강좌, 응시일, 응시 번호 순으로 출력한다.',"SELECT attempt_id,member_id,course_id,score-LAG(score) OVER(PARTITION BY member_id,course_id ORDER BY attempted_at,attempt_id) AS score_change FROM attempts WHERE score IS NOT NULL ORDER BY member_id,course_id,attempted_at,attempt_id",'윈도 계산 전에 NULL 점수를 제거하여 직전 응시가 아니라 직전 채점과 비교한다.');
add(academy,4,'회원별 누적 학습 시간','윈도 누적','activity','member_id,activity_date,cumulative_minutes','study 기록이 있는 회원·날짜별로 해당일까지의 누적 study 시간을 조회한다. 같은 날의 기록을 먼저 합친다. 회원 번호, 날짜 오름차순이다.',"WITH daily AS (SELECT member_id,activity_date,SUM(duration) AS minutes FROM activity WHERE kind='study' GROUP BY member_id,activity_date) SELECT member_id,activity_date,SUM(minutes) OVER(PARTITION BY member_id ORDER BY activity_date ROWS UNBOUNDED PRECEDING) AS cumulative_minutes FROM daily ORDER BY member_id,activity_date",'날짜 단위 결과가 필요하므로 행 단위 누적에 앞서 일별 집계를 수행한다.');
add(academy,4,'최초와 최종 채점 점수','조건부 피벗','attempts','member_id,course_id,first_score,last_score','채점된 응시가 있는 회원·강좌별 최초 및 최종 채점 점수를 조회한다. 응시일, 응시 번호 순으로 정하며 채점 한 건이면 두 값이 같다. 회원, 강좌 번호 오름차순이다.',"WITH ranked AS (SELECT member_id,course_id,score,ROW_NUMBER() OVER(PARTITION BY member_id,course_id ORDER BY attempted_at,attempt_id) AS first_rn,ROW_NUMBER() OVER(PARTITION BY member_id,course_id ORDER BY attempted_at DESC,attempt_id DESC) AS last_rn FROM attempts WHERE score IS NOT NULL) SELECT member_id,course_id,MAX(CASE WHEN first_rn=1 THEN score END) AS first_score,MAX(CASE WHEN last_rn=1 THEN score END) AS last_score FROM ranked GROUP BY member_id,course_id ORDER BY member_id,course_id",'양 방향 순번과 조건부 집계를 조합하면 LAST_VALUE의 기본 프레임에 의한 혼동을 피할 수 있다.');
add(academy,4,'강좌별 최고점 상위 회원 두 명','상위 N','attempts','course_id,member_id,best_score','각 강좌에서 회원별 최고 채점 점수가 높은 회원을 최대 두 명 조회한다. 점수가 같으면 회원 번호가 작은 회원을 우선하며 동점 전체를 포함하지 않는다. 강좌 번호, 최고점 내림차순, 회원 번호 오름차순이다.',"WITH best AS (SELECT course_id,member_id,MAX(score) AS best_score FROM attempts WHERE score IS NOT NULL GROUP BY course_id,member_id), ranked AS (SELECT course_id,member_id,best_score,ROW_NUMBER() OVER(PARTITION BY course_id ORDER BY best_score DESC,member_id) AS rn FROM best) SELECT course_id,member_id,best_score FROM ranked WHERE rn<=2 ORDER BY course_id,best_score DESC,member_id",'최대 두 명이라는 제한은 ROW_NUMBER에 적합하다. 회원 번호는 선택 시점과 출력 시점 모두 사용한다.');
add(academy,4,'전체 회원의 학습 백분위','CUME_DIST','members,activity','member_id,total_minutes,cumulative_pct','모든 회원의 study 총시간을 구하고, 전체 회원 중 자신 이하의 총시간을 가진 회원 비율을 백분율 소수 둘째 자리로 조회한다. 기록 없으면 총시간 0. 동점 회원은 같은 비율이다. 총시간, 회원 번호 오름차순이다.',"WITH totals AS (SELECT m.member_id,COALESCE(SUM(a.duration),0) AS total_minutes FROM members m LEFT JOIN activity a ON a.member_id=m.member_id AND a.kind='study' GROUP BY m.member_id) SELECT member_id,total_minutes,ROUND(100*CUME_DIST() OVER(ORDER BY total_minutes),2) AS cumulative_pct FROM totals ORDER BY total_minutes,member_id",'CUME_DIST는 동점의 마지막 위치까지 누적한 비율이다. 윈도 정렬에 회원 번호를 넣으면 동점 정책이 깨진다.');
add(academy,5,'가입 다음 날 학습 유지율','일별 코호트','members,activity','cohort_date,member_count,retained_count,retention_pct','가입 날짜별 전체 회원 수와 정확히 가입 다음 날 study 기록이 있는 회원 수, 유지율(백분율, 소수 둘째 자리)을 조회한다. 0분 study도 인정하고 여러 기록은 회원당 한 번만 센다. 가입일 오름차순이다.',"WITH flags AS (SELECT m.member_id,m.joined_at,EXISTS(SELECT 1 FROM activity a WHERE a.member_id=m.member_id AND a.kind='study' AND a.activity_date=DATE_ADD(m.joined_at,INTERVAL 1 DAY)) AS retained FROM members m) SELECT joined_at AS cohort_date,COUNT(*) AS member_count,SUM(retained) AS retained_count,ROUND(100.0*SUM(retained)/COUNT(*),2) AS retention_pct FROM flags GROUP BY joined_at ORDER BY cohort_date",'다음 활동일이 아닌 정확한 가입 다음 날을 검사한다. 활동하지 않은 가입자도 분모에 남는다.');
add(academy,5,'회원별 최장 연속 학습','최대 연속 구간','members,activity','member_id,longest_streak','모든 회원의 최장 연속 study 날짜 수를 조회한다. 같은 날 여러 기록은 하루이며 0분 study도 인정한다. login만 있는 날은 끊긴다. study 기록이 없으면 0. 회원 번호 오름차순이다.',"WITH days AS (SELECT DISTINCT member_id,activity_date FROM activity WHERE kind='study'), numbered AS (SELECT member_id,activity_date,ROW_NUMBER() OVER(PARTITION BY member_id ORDER BY activity_date) AS rn FROM days), lengths AS (SELECT member_id,COUNT(*) AS streak FROM numbered GROUP BY member_id,DATE_SUB(activity_date,INTERVAL rn DAY)), best AS (SELECT member_id,MAX(streak) AS longest_streak FROM lengths GROUP BY member_id) SELECT m.member_id,COALESCE(b.longest_streak,0) AS longest_streak FROM members m LEFT JOIN best b ON b.member_id=m.member_id ORDER BY m.member_id",'날짜-순번으로 연속 구간을 나눈 뒤 구간 길이의 최댓값을 구한다. 회원 목록에 다시 조인해 비활동 회원을 보존한다.');
add(academy,5,'모든 필수 강좌 완료자','관계 나눗셈','members,courses,enrollments','member_id,name','현재 필수(required=1)인 강좌를 모두 한 번 이상 완료한 회원을 조회한다. 같은 강좌의 미완료 재등록이 있어도 완료 이력이 있으면 인정한다. 필수 강좌가 없으면 모든 회원을 출력한다. 회원 번호 오름차순이다.',"SELECT m.member_id,m.name FROM members m WHERE NOT EXISTS(SELECT 1 FROM courses c WHERE c.required=1 AND NOT EXISTS(SELECT 1 FROM enrollments e WHERE e.member_id=m.member_id AND e.course_id=c.course_id AND e.completed_at IS NOT NULL)) ORDER BY m.member_id",'완료하지 않은 필수 강좌가 존재하지 않는지 검사한다. 빈 필수 집합과 재등록을 별도 예외 없이 처리한다.');
add(academy,5,'활동일 기반 학습 세션','세션화','activity','member_id,session_number,start_date,end_date,total_minutes','회원별 모든 활동을 날짜 단위로 합친 뒤 인접 활동 날짜 간 차이가 2일을 초과하면 새 세션으로 나눈다. login도 활동일이며 total_minutes는 study만 합산한다. 회원별 세션 번호는 1부터 시작한다. 회원 번호, 세션 번호 오름차순이다.',"WITH daily AS (SELECT member_id,activity_date,SUM(CASE WHEN kind='study' THEN duration ELSE 0 END) AS minutes FROM activity GROUP BY member_id,activity_date), gaps AS (SELECT member_id,activity_date,minutes,LAG(activity_date) OVER(PARTITION BY member_id ORDER BY activity_date) AS previous_date FROM daily), numbered AS (SELECT member_id,activity_date,minutes,SUM(CASE WHEN previous_date IS NULL OR DATEDIFF(activity_date,previous_date)>2 THEN 1 ELSE 0 END) OVER(PARTITION BY member_id ORDER BY activity_date ROWS UNBOUNDED PRECEDING) AS session_number FROM gaps) SELECT member_id,session_number,MIN(activity_date) AS start_date,MAX(activity_date) AS end_date,SUM(minutes) AS total_minutes FROM numbered GROUP BY member_id,session_number ORDER BY member_id,session_number",'먼저 새 세션 시작 여부를 만들고 누적합으로 세션 번호를 부여한다. 2일 차이는 유지하고 3일 차이부터 분리한다.');
add(academy,5,'강좌별 최고점 중앙값','집계 후 중앙값','courses,attempts','course_id,median_best_score','모든 강좌에 대해 회원별 최고 채점 점수들의 중앙값을 소수 둘째 자리로 조회한다. 짝수 인원이면 가운데 두 점수의 평균, 채점된 회원이 없으면 NULL이다. 강좌 번호 오름차순이다.',"WITH best AS (SELECT course_id,member_id,MAX(score) AS score FROM attempts WHERE score IS NOT NULL GROUP BY course_id,member_id), ranked AS (SELECT course_id,score,ROW_NUMBER() OVER(PARTITION BY course_id ORDER BY score,member_id) AS rn,COUNT(*) OVER(PARTITION BY course_id) AS n FROM best), medians AS (SELECT course_id,ROUND(AVG(score),2) AS median_best_score FROM ranked WHERE rn IN (FLOOR((n+1)/2),FLOOR((n+2)/2)) GROUP BY course_id) SELECT c.course_id,m.median_best_score FROM courses c LEFT JOIN medians m ON m.course_id=c.course_id ORDER BY c.course_id",'최고점으로 응시 빈도를 제거한 뒤 위치 기반 중앙값을 계산한다. 채점 없는 강좌는 마지막 LEFT JOIN으로 복원한다.');
add(academy,5,'누적 60분 최초 달성일','누적 임계값','members,activity','member_id,reached_at','모든 회원에 대해 전체 기간 study 시간이 날짜 순 누적으로 처음 60분 이상 된 날짜를 조회한다. 같은 날의 기록을 모두 합친 뒤 판단한다. 달성하지 못하면 NULL. 회원 번호 오름차순이다.',"WITH daily AS (SELECT member_id,activity_date,SUM(duration) AS minutes FROM activity WHERE kind='study' GROUP BY member_id,activity_date), running AS (SELECT member_id,activity_date,SUM(minutes) OVER(PARTITION BY member_id ORDER BY activity_date ROWS UNBOUNDED PRECEDING) AS total FROM daily), reached AS (SELECT member_id,MIN(activity_date) AS reached_at FROM running WHERE total>=60 GROUP BY member_id) SELECT m.member_id,r.reached_at FROM members m LEFT JOIN reached r ON r.member_id=m.member_id ORDER BY m.member_id",'임계값을 넘는 일별 누적 행 중 첫 날짜를 선택한다. 한 활동의 시간이나 일별 시간만으로 판단하면 누적 목표를 놓친다.');
add(academy,5,'같은 강좌 집합을 수강한 회원 쌍','집합 동등성','members,enrollments','member_a,member_b','서로 다른 두 회원의 전체 기간 등록 강좌 집합이 정확히 같은 쌍을 조회한다. 재등록은 집합에 영향을 주지 않는다. 두 회원 모두 적어도 한 강좌에 등록했어야 한다. 작은 회원 번호가 member_a이며 member_a, member_b 오름차순이다.',"WITH registered AS (SELECT DISTINCT member_id,course_id FROM enrollments) SELECT a.member_id AS member_a,b.member_id AS member_b FROM members a JOIN members b ON a.member_id<b.member_id WHERE EXISTS(SELECT 1 FROM registered x WHERE x.member_id=a.member_id) AND NOT EXISTS(SELECT 1 FROM registered x WHERE x.member_id=a.member_id AND NOT EXISTS(SELECT 1 FROM registered y WHERE y.member_id=b.member_id AND y.course_id=x.course_id)) AND NOT EXISTS(SELECT 1 FROM registered y WHERE y.member_id=b.member_id AND NOT EXISTS(SELECT 1 FROM registered x WHERE x.member_id=a.member_id AND x.course_id=y.course_id)) ORDER BY member_a,member_b",'서로 양쪽 집합의 차집합이 비어야 동일하다. 한 방향만 검사하면 진부분집합인 회원도 잘못 포함한다.');
// 공집합과 0 나눗셈, 상품 없는 주문까지 별도 세트로 검증한다.
shop.datasets.push({name:'hidden_empty_relations',rows:{customers:[[1,'영원','서울','2024-01-01'],[2,'조용',null,'2024-01-31']],products:[[1,'무료컵','생활',0]],orders:[[1,1,'2024-01-01','paid'],[2,1,'2024-01-02','paid'],[3,1,'2024-01-03','paid']],order_items:[[1,1,1,0]]}});
academy.datasets.push({name:'hidden_ungraded',rows:{members:[[1,'빈점수',null,'2024-01-01'],[2,'새회원','서울','2024-01-01']],courses:[[1,'SQL 시작','데이터',1],[2,'독서','교양',0]],enrollments:[[1,1,1,'2024-01-01',null]],attempts:[[1,1,1,'2024-01-01',null],[2,1,1,'2024-01-02',null]],activity:[[1,1,'2024-01-01','login',0],[2,1,'2024-01-03','login',0],[3,1,'2024-01-06','login',0]]}});
// 같은 비어 있지 않은 등록 집합을 가진 회원 쌍도 숨김 데이터에서 검증한다.
academy.datasets.find(d=>d.name==='hidden_sparse').rows.enrollments.push([50,30,20,'2024-03-01',null]);
// 공개 기대값은 정답 SQL 실행 결과를 복사하지 않고 아래에서 별도 산술·배열 연산으로 계산한다.
const checks=[];
const sc=shop.datasets[0].rows, ac=academy.datasets[0].rows;
checks.push({id:'level1_01',rows:sc.customers.filter(r=>r[2]==='서울').map(r=>r.slice(0,2))});
checks.push({id:'level1_08',rows:ac.courses.filter(r=>r[3]===1).map(r=>r.slice(0,2))});
checks.push({id:'level2_07',rows:[...new Set(sc.order_items.map(r=>r[0]))].sort((a,b)=>a-b).map(id=>{const rows=sc.order_items.filter(r=>r[0]===id);return [id,rows.reduce((s,r)=>s+r[2],0),rows.reduce((s,r)=>s+r[2]*r[3],0)]})});
checks.push({id:'level2_12',rows:[...new Set(ac.activity.map(r=>r[1]))].sort((a,b)=>a-b).map(id=>[id,new Set(ac.activity.filter(r=>r[1]===id).map(r=>r[2])).size])});
checks.push({id:'level3_01',rows:sc.customers.map(c=>[c[0],c[1],sc.orders.filter(o=>o[1]===c[0]&&o[3]==='paid').length])});
checks.push({id:'level3_08',rows:ac.courses.map(c=>[c[0],c[1],new Set(ac.enrollments.filter(e=>e[2]===c[0]).map(e=>e[1])).size])});
checks.push({id:'level4_01',rows:sc.orders.filter(o=>o[3]==='paid').sort((a,b)=>a[1]-b[1]||a[2].localeCompare(b[2])||a[0]-b[0]).map((o,i,all)=>[o[1],o[0],all.slice(0,i+1).filter(p=>p[1]===o[1]).length])});
checks.push({id:'level4_09',rows:[...new Set(ac.attempts.map(a=>a[1]+'_'+a[2]))].map(key=>{const [member,course]=key.split('_').map(Number);const latest=ac.attempts.filter(a=>a[1]===member&&a[2]===course).sort((a,b)=>b[3].localeCompare(a[3])||b[0]-a[0])[0];return [member,course,latest[0],latest[4]]}).sort((a,b)=>a[0]-b[0]||a[1]-b[1])});
checks.push({id:'level5_03',rows:sc.customers.filter(c=>sc.products.filter(p=>p[2]==='문구').every(p=>sc.order_items.some(i=>i[1]===p[0]&&sc.orders.some(o=>o[0]===i[0]&&o[1]===c[0]&&o[3]==='paid')))).map(c=>c.slice(0,2))});
checks.push({id:'level5_10',rows:ac.members.filter(m=>ac.courses.filter(c=>c[3]===1).every(c=>ac.enrollments.some(e=>e[1]===m[0]&&e[2]===c[0]&&e[4]!==null))).map(m=>m.slice(0,2))});
// 기존 문제 ID와 정답은 유지하고 단계별 새 문제만 뒤에 추가한다.
for (const source of ['extra-basic','extra-middle','extra-advanced']) {
 for (const {pack,expectedRows,wrongSql,...problem} of require(`./${source}.cjs`)) {
  const target={shop,academy}[pack];
  if (!target) throw new Error(`알 수 없는 문제 팩: ${pack}`);
  target.problems.push(problem);
  if (expectedRows) checks.push({id:problem.id,rows:expectedRows});
 }
}
for(const pack of [shop,academy]) fs.writeFileSync(path.join(__dirname,pack.id+'.json'),JSON.stringify(pack,null,2)+'\n');
fs.writeFileSync(path.join(__dirname,'checks.json'),JSON.stringify(checks,null,2)+'\n');
const packs=['shop','academy'].map(id=>JSON.parse(fs.readFileSync(path.join(__dirname,id+'.json'),'utf8')));
const problems=packs.flatMap(p=>p.problems);
const assert=require('node:assert/strict');
assert.equal(problems.length,300);assert.equal(new Set(problems.map(p=>p.id)).size,300);
for(let level=1;level<=5;level++)assert.equal(problems.filter(p=>p.level===level).length,60);
for(const pack of packs){assert.ok(pack.datasets.length>=3);for(const data of pack.datasets)for(const table of pack.tables){assert.ok(Array.isArray(data.rows[table.name]));for(const row of data.rows[table.name])assert.equal(row.length,table.columns.length);}for(const p of pack.problems){assert.ok(p.tables.every(t=>pack.tables.some(x=>x.name===t)));assert.ok(p.columns.length>0);assert.match(p.solution,/^(SELECT|WITH) /);}}
for(const check of checks){const p=problems.find(p=>p.id===check.id);assert.ok(p);assert.ok(check.rows.every(row=>row.length===p.columns.length));}
console.log(`검증 통과: 2개 팩, 300개 고유 문제, 단계별 60개, 각 팩 4개 데이터 세트, 공개 독립 검산 ${checks.length}개`);
