// 각 정의는 단일 테이블만 읽으며 출력 열과 순서를 명시한다.
const problems = [];
const counts = {1:14,2:14};
function add(level,pack,table,title,topic,columns,request,select,tail,order,explanation){
 const solution=`SELECT ${select} FROM ${table}${tail?' '+tail:''} ORDER BY ${order}`;
 problems.push({pack,id:`level${level}_${++counts[level]}`,level,title,topic,tables:[table],columns:columns.split(','),ordered:true,description:`${request} 결과 열은 ${columns} 순서다. 정렬 기준은 ${order}이며 DESC는 내림차순, 나머지는 오름차순이다. 날짜 범위를 별도로 지정하지 않으면 전체 기간을 대상으로 한다.`,solution,explanation,hints:[`핵심 개념: ${topic}. 결과 한 행이 나타내는 대상을 먼저 확인하세요.`,`${explanation} ${table}에서 필요한 행을 고른 후 출력식을 계산하고 지정된 기준으로 정렬하세요.`,`-- 주석 빈칸에 출력식과 필요한 조건을 채우세요.\nSELECT /* ${columns} 출력식 */ FROM ${table}\n${tail}\nORDER BY ${order};`],starter:'-- 조건과 출력 열을 확인하세요.\nSELECT '});
}
const a=(...x)=>add(1,...x), b=(...x)=>add(2,...x);
a('shop','customers','도시 제외와 미입력 포함','부정 조건과 NULL','customer_id,city','서울이 아닌 고객과 도시 미입력 고객을 조회한다. NULL은 그대로 출력한다.','customer_id,city',"WHERE city<>'서울' OR city IS NULL",'customer_id','부등 비교만으로는 NULL 행을 포함할 수 없어 OR IS NULL을 결합한다.');
a('shop','products','분류별 서로 다른 가격표','복합 DISTINCT','category,price','분류와 가격 조합을 중복 없이 조회한다.','DISTINCT category,price','','category,price','DISTINCT는 선택한 두 열의 조합에 적용된다.');
a('shop','customers','주소 라벨 완성','COALESCE와 CONCAT','customer_id,address_label','고객별 이름 뒤에 괄호로 도시를 붙인다. 도시가 NULL이면 미입력을 넣는다. 예: 가람(서울).','customer_id,CONCAT(name,\'(\',COALESCE(city,\'미입력\'),\')\') AS address_label','','customer_id','NULL을 먼저 치환해야 CONCAT 전체가 NULL이 되지 않는다.');
a('shop','products','가운데 가격 페이지','LIMIT OFFSET','product_id,price','가격 오름차순으로 정렬한 목록의 첫 두 상품을 건너뛰고 다음 세 상품만 조회한다. 동점은 상품 번호순이다. 부족하면 있는 행만 반환한다.','product_id,price','','price,product_id LIMIT 3 OFFSET 2','OFFSET은 건너뛸 행 수이며 동점 기준까지 지정해야 페이지가 안정적이다.');
a('shop','orders','주문일 역순 확인','혼합 방향 정렬','order_id,ordered_at,customer_id','모든 주문을 최근 날짜 먼저 조회하고 같은 날에는 고객 번호, 주문 번호 순으로 조회한다. 상태는 구분하지 않는다.','order_id,ordered_at,customer_id','','ordered_at DESC,customer_id,order_id','각 정렬 열마다 방향을 독립적으로 지정한다.');
a('shop','products','한 글자 상품명','LIKE 밑줄','product_id,name','이름이 정확히 한 글자인 상품을 조회한다.','product_id,name',"WHERE name LIKE '_'",'product_id','밑줄 하나는 정확히 한 글자와 대응한다.');
a('academy','courses','기초로 끝나는 강좌','접미어 검색','course_id,title','강좌명이 기초로 끝나는 강좌를 조회한다.','course_id,title',"WHERE title LIKE '%기초'",'course_id','앞쪽에만 퍼센트를 넣으면 접미어를 검색한다.');
a('academy','courses','공백 없는 강좌명','NOT LIKE','course_id,title','강좌명에 일반 공백 문자가 전혀 없는 강좌를 조회한다.','course_id,title',"WHERE title NOT LIKE '% %'",'course_id','포함 패턴을 NOT LIKE로 부정한다.');
a('academy','attempts','재검토 점수와 미채점','괄호 조건','attempt_id,score','1번 강좌 응시 중 점수가 60 미만이거나 미채점인 행을 조회한다. 미채점 점수는 NULL 그대로 둔다.','attempt_id,score','WHERE course_id=1 AND (score<60 OR score IS NULL)','attempt_id','OR 조건을 괄호로 묶어 강좌 필터가 두 경우 모두에 적용되게 한다.');
a('academy','enrollments','등록 당일 완료','열 간 비교','enrollment_id,member_id','등록일과 완료일이 같은 수강을 조회한다. 완료일 NULL은 제외한다.','enrollment_id,member_id','WHERE completed_at=enrolled_at','enrollment_id','두 날짜 열을 직접 비교할 수 있으며 NULL 비교는 참이 되지 않는다.');
a('academy','attempts','점수 없는 응시를 마지막에','NULL 정렬','attempt_id,score','모든 응시를 채점된 행 먼저, 점수 내림차순으로 조회한다. 미채점은 마지막이며 점수가 같거나 모두 NULL이면 응시 번호순이다.','attempt_id,score','','score IS NULL,score DESC,attempt_id','NULL 여부의 불리언 식을 첫 정렬 키로 쓰면 NULL의 위치를 제어한다.');
a('shop','customers','가입 연월 문자열','DATE_FORMAT','customer_id,join_month','각 고객의 가입일을 YYYY-MM 문자열로 변환한다.','customer_id,DATE_FORMAT(joined_at,\'%Y-%m\') AS join_month','','customer_id','연도와 월을 함께 출력하면 다른 해의 같은 달이 구별된다.');
a('shop','orders','주문일 다음날 안내','DATE_ADD','order_id,next_date','상태와 무관하게 주문일 다음날을 계산한다.','order_id,DATE_ADD(ordered_at,INTERVAL 1 DAY) AS next_date','','order_id','날짜 연산은 월말과 연말의 경계를 자동 처리한다.');
a('academy','members','가입일의 연도와 월','날짜 부분 추출','member_id,join_year,join_month','가입일에서 연도와 월을 정수로 추출한다.','member_id,YEAR(joined_at) AS join_year,MONTH(joined_at) AS join_month','','member_id','YEAR와 MONTH는 날짜의 해당 부분을 정수로 반환한다.');
a('academy','courses','강좌명 글자 수','CHAR_LENGTH','course_id,title_length','강좌명의 글자 수를 계산한다. 공백도 한 글자로 센다.','course_id,CHAR_LENGTH(title) AS title_length','','course_id','한글의 바이트 수가 아니라 글자 수를 세므로 CHAR_LENGTH를 쓴다.');
a('academy','members','이름 앞글자만 공개','LEFT','member_id,masked_name','회원 이름의 첫 글자 뒤에 별표 두 개를 붙여 표시한다. 이름 길이에 관계없이 별표는 두 개다.','member_id,CONCAT(LEFT(name,1),\'**\') AS masked_name','','member_id','LEFT로 첫 글자를 추출한 다음 고정 문자열을 연결한다.');
a('shop','products','천원 단위 가격','ROUND','product_id,price_thousands','가격을 천원 단위로 변환하고 소수 첫째 자리로 반올림한다.','product_id,ROUND(price/1000,1) AS price_thousands','','product_id','단위 변환 후 필요한 자릿수에서 반올림한다.');
a('shop','order_items','서로 다른 주문 상품 연결','DISTINCT 복합 키','order_id,product_id','주문과 상품 번호 조합을 한 번씩만 출력한다. 수량과 단가는 출력하지 않으며 주문 상태를 구분하지 않는다.','DISTINCT order_id,product_id','','order_id,product_id','주문 안에서 반복된 상품 행을 두 열의 조합으로 제거한다.');
a('shop','order_items','여러 개 구매한 상세 행','행 산술과 필터','order_id,product_id,quantity,line_amount','수량이 2 이상인 상품 행과 수량 곱하기 당시 단가로 계산한 행 금액을 조회한다. 중복 행은 유지한다. 모든 출력값이 같은 행의 순서는 구별하지 않는다.','order_id,product_id,quantity,quantity*unit_price AS line_amount','WHERE quantity>=2','order_id,product_id,quantity,line_amount','집계하지 않고 각 원본 행의 수량과 단가를 곱한다.');
a('shop','products','만원으로 살 수 있는 개수','FLOOR와 0 제외','product_id,affordable_quantity','가격이 양수인 상품마다 10000원으로 살 수 있는 최대 정수 개수를 구한다. 무료 상품은 제외한다.','product_id,FLOOR(10000/price) AS affordable_quantity','WHERE price>0','product_id','나눗셈 결과를 내림하고 분모가 0인 행을 먼저 제외한다.');
a('shop','products','만원 구매 후 잔돈','MOD','product_id,remainder_amount','양수 가격인 상품을 10000원 한도에서 최대한 구매했을 때 남는 금액을 구한다. 무료 상품은 제외한다.','product_id,MOD(10000,price) AS remainder_amount','WHERE price>0','product_id','나머지 연산은 정수 개수 구매 후 남는 금액을 계산한다.');
a('academy','activity','15분 단위 묶음','정수 나눗셈','activity_id,full_blocks','study 기록마다 완전히 채운 15분 구간 수를 구한다. 15분 미만은 0이다.','activity_id,duration DIV 15 AS full_blocks',"WHERE kind='study'",'activity_id','DIV는 나눗셈의 정수 몫만 반환한다.');
a('academy','enrollments','완료 날짜 기본 표시','IFNULL','enrollment_id,completed_label','완료일을 YYYY-MM-DD 문자열로 표시하고 미완료는 진행중으로 표시한다.','enrollment_id,IFNULL(DATE_FORMAT(completed_at,\'%Y-%m-%d\'),\'진행중\') AS completed_label','','enrollment_id','날짜를 문자열로 변환한 뒤 미완료 대체 문구를 넣는다.');
a('academy','courses','강좌명 공백 제거','REPLACE','course_id,compact_title','강좌명에서 모든 일반 공백을 제거한다. 다른 문자는 그대로 유지한다.','course_id,REPLACE(title,\' \',\'\') AS compact_title','','course_id','REPLACE는 지정한 부분 문자열의 모든 출현을 바꾼다.');
a('academy','courses','영문 강좌명 소문자화','LOWER','course_id,normalized_title','강좌명에 포함된 영문자를 소문자로 변환한다. 한글과 공백은 유지한다.','course_id,LOWER(title) AS normalized_title','','course_id','LOWER는 문자 대소문자를 정규화한다.');
a('shop','orders','결제 주문의 고객 날짜 목록','DISTINCT와 필터','customer_id,ordered_at','paid 주문을 한 고객과 날짜 조합을 한 번씩 출력한다. 같은 날 같은 고객의 여러 주문은 하나로 합친다.','DISTINCT customer_id,ordered_at',"WHERE status='paid'",'customer_id,ordered_at','행 조건 적용 뒤 선택한 두 열의 중복을 제거한다.');
a('shop','customers','서로 떨어진 가입 기간','OR 기간','customer_id,joined_at','2024년 1월 1일 미만에 가입했거나 2024년 3월 1일 이상에 가입한 고객을 조회한다. 두 기간 사이의 가입은 제외한다.','customer_id,joined_at',"WHERE joined_at<'2024-01-01' OR joined_at>='2024-03-01'",'customer_id','겹치지 않는 두 기간은 OR로 결합한다.');
a('shop','products','복합 판매 대상','AND OR 우선순위','product_id,name','문구 상품 전체와 가격이 2500 이상인 생활 상품을 조회한다. 다른 분류는 제외한다.','product_id,name',"WHERE category='문구' OR (category='생활' AND price>=2500)",'product_id','분류별로 다른 조건을 OR로 연결하고 필요한 AND를 묶는다.');
a('academy','attempts','합격선까지 남은 점수','뺄셈','attempt_id,missing_points','채점된 점수가 80 미만인 응시에 대해 80점까지 부족한 점수를 구한다. NULL은 제외한다.','attempt_id,80-score AS missing_points','WHERE score<80','attempt_id','목표에서 현재 값을 빼면 부족분을 얻는다.');
a('academy','attempts','대상 밖 강좌의 채점 응시','NOT IN과 NULL','attempt_id,course_id,score','강좌 번호가 1과 2가 아니며 채점이 끝난 응시만 조회한다.','attempt_id,course_id,score','WHERE course_id NOT IN (1,2) AND score IS NOT NULL','attempt_id','제외 목록과 채점 여부는 별개의 조건으로 결합한다.');
a('academy','enrollments','다음 달 이후 완료','날짜 열 관계','enrollment_id,enrolled_at,completed_at','등록일이 속한 달의 말일보다 뒤에 완료된 등록을 조회한다. 미완료는 제외한다.','enrollment_id,enrolled_at,completed_at','WHERE completed_at>LAST_DAY(enrolled_at)','enrollment_id','완료일을 등록 월의 마지막 날과 비교하면 달을 넘긴 완료를 찾는다.');
a('shop','customers','가입 월의 시작일','날짜 서식','customer_id,month_start','가입일이 속한 달의 1일을 YYYY-MM-DD 문자열로 출력한다.','customer_id,DATE_FORMAT(joined_at,\'%Y-%m-01\') AS month_start','','customer_id','서식의 일 부분을 고정하면 월 시작일 문자열을 얻는다.');
a('academy','activity','주말 활동','WEEKDAY','activity_id,activity_date','토요일 또는 일요일에 남긴 활동을 종류와 시간에 관계없이 조회한다.','activity_id,activity_date','WHERE WEEKDAY(activity_date) IN (5,6)','activity_id','WEEKDAY는 월요일 0부터 일요일 6까지 반환한다.');
a('shop','orders','매월 첫날 주문','DAYOFMONTH','order_id,ordered_at','매월 1일에 발생한 주문을 상태와 무관하게 조회한다.','order_id,ordered_at','WHERE DAYOFMONTH(ordered_at)=1','order_id','날짜의 일 부분을 추출해 월에 관계없는 조건을 적용한다.');
a('academy','members','가입일 요일 번호','WEEKDAY 출력','member_id,weekday_number','가입일의 요일을 월요일 0부터 일요일 6까지의 정수로 출력한다.','member_id,WEEKDAY(joined_at) AS weekday_number','','member_id','요일 함수마다 번호 체계가 다르므로 요구한 체계에 맞춘다.');
a('shop','products','상품 식별 라벨','LPAD','product_id,product_code','상품 번호를 최소 네 자리로 왼쪽에 0을 채워 표시한다. 번호가 네 자리보다 길면 원래 번호 문자열을 유지한다.','product_id,LPAD(CAST(product_id AS CHAR),GREATEST(4,CHAR_LENGTH(CAST(product_id AS CHAR))),\'0\') AS product_code','','product_id','LPAD의 길이를 원본 길이 이상으로 잡아 긴 번호가 잘리지 않게 한다.');
a('academy','courses','첫 단어 추출','SUBSTRING_INDEX','course_id,first_word','강좌명에서 첫 일반 공백 이전 문자열을 구한다. 공백이 없으면 강좌명 전체를 반환한다.','course_id,SUBSTRING_INDEX(title,\' \',1) AS first_word','','course_id','구분자가 없으면 SUBSTRING_INDEX는 원본 문자열을 반환한다.');
a('shop','customers','가입 기준일까지의 경과 일수','DATEDIFF 기준일','customer_id,elapsed_days','2024년 3월 1일까지 가입한 고객에 대해 기준일 2024년 3월 1일에서 가입일을 뺀 일수를 계산한다. 당일은 0이며 기준일 가입을 포함한다.','customer_id,DATEDIFF(\'2024-03-01\',joined_at) AS elapsed_days',"WHERE joined_at<='2024-03-01'",'customer_id','고정 기준일을 사용하면 실행 날짜에 관계없이 결과를 재현한다.');
a('academy','activity','양수 학습 시간을 긴 순서로','다중 조건과 정렬','activity_id,duration','study이면서 시간이 0보다 큰 활동만 시간 내림차순으로 조회한다. 동점은 활동 번호순이다.','activity_id,duration',"WHERE kind='study' AND duration>0",'duration DESC,activity_id','활동 종류와 측정값 조건을 모두 만족하는 행만 선택한다.');
a('academy','attempts','점수 백분율 문자열','문자열 결합','attempt_id,score_label','채점된 응시의 정수 점수 뒤에 퍼센트 기호를 붙인다. 미채점은 제외한다.','attempt_id,CONCAT(score,\'%\') AS score_label','WHERE score IS NOT NULL','attempt_id','CONCAT은 수치를 표시용 문자열로 연결한다.');
a('shop','products','천원 경계가 아닌 가격','나머지 필터','product_id,price','가격이 1000의 배수가 아닌 상품을 조회한다. 0은 배수이므로 제외된다.','product_id,price','WHERE MOD(price,1000)<>0','product_id','나머지가 0이 아니면 해당 단위로 나누어떨어지지 않는다.');
a('academy','enrollments','다음 달 같은 날짜 안내','월 간격과 말일 보정','enrollment_id,reminder_date','각 등록일로부터 한 달 뒤 날짜를 조회한다. 다음 달에 같은 일이 없으면 그달 마지막 날로 보정한다. 완료 여부는 구분하지 않는다.','enrollment_id,DATE_ADD(enrolled_at,INTERVAL 1 MONTH) AS reminder_date','','enrollment_id','한 달은 고정된 30일과 다르다. 월 간격 연산은 존재하지 않는 날짜를 월말로 보정한다.');
a('shop','customers','도시 있는 최신 가입 두 명','필터 뒤 LIMIT','customer_id,joined_at','도시를 입력한 고객 중 가입일이 가장 최근인 최대 두 명을 조회한다. 같은 가입일에는 고객 번호가 작은 고객을 먼저 선택한다.','customer_id,joined_at','WHERE city IS NOT NULL','joined_at DESC,customer_id LIMIT 2','대상 고객을 먼저 거른 다음 정렬한 결과에서 두 행을 선택한다.');
a('academy','attempts','중간 점수의 열린 구간','엄격한 경계','attempt_id,score','점수가 60보다 크고 80보다 작은 채점 응시를 조회한다. 60과 80 및 NULL은 제외한다.','attempt_id,score','WHERE score>60 AND score<80','attempt_id','양 끝을 제외하는 구간에는 BETWEEN 대신 엄격한 부등호를 쓴다.');
a('shop','orders','고객 번호별 취소 이력 행','상태 제외','order_id,customer_id,ordered_at','paid 상태가 아닌 주문을 고객 번호 오름차순, 같은 고객이면 최근 주문일 먼저 조회한다. 같은 날짜에는 주문 번호순이다. 상태 도메인은 paid와 canceled다.','order_id,customer_id,ordered_at',"WHERE status<>'paid'",'customer_id,ordered_at DESC,order_id','상태 도메인이 정해져 있을 때 부등 조건으로 반대 상태를 선택한다.');
a('academy','members','이름 두 번째 글자','SUBSTRING','member_id,second_character','회원 이름의 두 번째 글자를 출력한다. 두 번째 글자가 없으면 빈 문자열이다.','member_id,SUBSTRING(name,2,1) AS second_character','','member_id','문자열 위치는 1부터 시작하며 길이 1로 한 글자를 추출한다.');
b('shop','customers','도시 입력률','COUNT 분모','total_customers,known_cities,known_percent','전체 고객 수와 도시가 NULL이 아닌 고객 수, 도시 입력 비율의 백분율을 소수 둘째 자리로 구한다. 고객이 없으면 비율은 NULL이다. 한 행을 출력한다.','COUNT(*) AS total_customers,COUNT(city) AS known_cities,ROUND(100.0*COUNT(city)/NULLIF(COUNT(*),0),2) AS known_percent','','total_customers','전체 행 수와 NULL을 제외한 열 개수를 서로 다른 분모와 분자로 사용한다.');
b('shop','products','분류별 가격 폭','MIN MAX','category,price_gap','분류별 최고 가격에서 최저 가격을 뺀 가격 폭을 계산한다. 상품 하나인 분류는 0이다.','category,MAX(price)-MIN(price) AS price_gap','GROUP BY category','category','두 극값의 차이는 그룹 내부 가격 범위를 나타낸다.');
b('shop','orders','고객별 첫 주문과 마지막 주문','날짜 극값','customer_id,first_order,last_order','주문이 있는 고객별 첫 주문일과 마지막 주문일을 구한다. 모든 상태를 포함한다.','customer_id,MIN(ordered_at) AS first_order,MAX(ordered_at) AS last_order','GROUP BY customer_id','customer_id','날짜 열의 최솟값과 최댓값은 최초일과 최종일이다.');
b('shop','orders','하루 중복 주문의 고객 날짜','복합 그룹 HAVING','customer_id,ordered_at,order_count','같은 고객이 같은 날짜에 두 건 이상 주문한 조합과 주문 수를 조회한다. 모든 상태를 포함한다.','customer_id,ordered_at,COUNT(*) AS order_count','GROUP BY customer_id,ordered_at HAVING COUNT(*)>=2','customer_id,ordered_at','고객과 날짜를 함께 묶어 같은 날의 반복 주문을 센다.');
b('shop','order_items','상품별 가중 평균 판매 단가','가중 평균','product_id,weighted_price','상품별 총 구매 금액을 총수량으로 나눈 가중 평균 단가를 소수 둘째 자리로 구한다. 모든 상세 행과 중복 행을 포함하며 주문 상태는 구분하지 않는다.','product_id,ROUND(SUM(quantity*unit_price)/SUM(quantity),2) AS weighted_price','GROUP BY product_id','product_id','수량 가중 평균은 행별 단가의 단순 평균과 다르다.');
b('shop','order_items','상품별 서로 다른 주문 수','고유 키 개수','product_id,order_count','상세 행에 등장한 상품별 서로 다른 주문 번호 수를 조회한다. 같은 주문에 중복된 상품 행은 한 주문으로 센다. 모든 상태를 포함한다.','product_id,COUNT(DISTINCT order_id) AS order_count','GROUP BY product_id','product_id','상품별 주문 수를 셀 때 주문 번호에 DISTINCT를 적용한다.');
b('shop','order_items','반복 저장된 상품 조합','중복 행 탐지','order_id,product_id,line_count','같은 주문과 상품 번호가 상세 테이블에 두 행 이상 존재하는 조합을 출력한다. 수량과 단가가 달라도 같은 조합이다. 모든 상태를 포함한다.','order_id,product_id,COUNT(*) AS line_count','GROUP BY order_id,product_id HAVING COUNT(*)>1','order_id,product_id','복합 키의 행 수가 1보다 큰 그룹을 찾는다.');
b('shop','products','같은 가격을 가진 상품 묶음','가격별 그룹','price,product_count','두 상품 이상이 공유하는 가격과 해당 가격의 상품 수를 조회한다. 분류는 구분하지 않는다.','price,COUNT(*) AS product_count','GROUP BY price HAVING COUNT(*)>=2','price','식별자가 아닌 가격을 그룹 키로 삼아 동가 상품을 찾는다.');
b('shop','customers','연도별 가입 도시 다양성','NULL 제외 고유 개수','join_year,customer_count,city_count','가입 연도별 고객 수와 서로 다른 입력 도시 수를 구한다. NULL 도시는 도시 수에 포함하지 않지만 고객 수에는 포함한다.','YEAR(joined_at) AS join_year,COUNT(*) AS customer_count,COUNT(DISTINCT city) AS city_count','GROUP BY YEAR(joined_at)','join_year','COUNT DISTINCT는 NULL을 제외하고 중복된 도시를 한 번 센다.');
b('shop','orders','취소도 결제도 있는 고객','조건부 HAVING','customer_id,paid_count,canceled_count','paid와 canceled 주문이 각각 한 건 이상 있는 고객과 상태별 주문 수를 조회한다.','customer_id,SUM(status=\'paid\') AS paid_count,SUM(status=\'canceled\') AS canceled_count',"GROUP BY customer_id HAVING SUM(status='paid')>0 AND SUM(status='canceled')>0",'customer_id','상태를 WHERE에서 제거하지 않고 집계 후 양쪽 상태의 존재를 확인한다.');
b('shop','orders','고객별 취소율','조건부 비율','customer_id,cancel_percent','주문이 있는 고객별 전체 주문 중 canceled 주문의 백분율을 소수 둘째 자리로 구한다. 취소가 없으면 0이다.','customer_id,ROUND(100.0*SUM(status=\'canceled\')/COUNT(*),2) AS cancel_percent','GROUP BY customer_id','customer_id','그룹 전체 주문 수를 분모로 두고 취소 건수를 분자로 둔다.');
b('shop','orders','월별 구매 고객 수','월 단위 고유 고객','order_month,buyer_count','paid 주문이 있는 연월별 고유 고객 수를 구한다. 연월은 YYYY-MM이며 같은 고객의 여러 주문은 한 명으로 센다.','DATE_FORMAT(ordered_at,\'%Y-%m\') AS order_month,COUNT(DISTINCT customer_id) AS buyer_count',"WHERE status='paid' GROUP BY DATE_FORMAT(ordered_at,'%Y-%m')",'order_month','월별 주문 행을 묶은 뒤 고객 번호의 중복을 제거해 센다.');
b('shop','order_items','여러 상품 종류를 담은 주문','고유 개수 HAVING','order_id,product_count','서로 다른 상품을 두 종류 이상 담은 주문과 상품 종류 수를 구한다. 중복 행과 수량은 종류 수를 늘리지 않으며 상태는 구분하지 않는다.','order_id,COUNT(DISTINCT product_id) AS product_count','GROUP BY order_id HAVING COUNT(DISTINCT product_id)>=2','order_id','행 수 대신 고유 상품 수를 집계한 뒤 조건을 적용한다.');
b('shop','order_items','판매 단가가 달라진 상품','극값 비교 HAVING','product_id,min_price,max_price','상세 행의 당시 단가가 서로 다른 값으로 기록된 상품과 최저·최고 단가를 구한다. 주문 상태는 구분하지 않는다.','product_id,MIN(unit_price) AS min_price,MAX(unit_price) AS max_price','GROUP BY product_id HAVING MIN(unit_price)<MAX(unit_price)','product_id','최솟값이 최댓값보다 작으면 최소 두 가격이 존재한다.');
b('shop','customers','상반기 하반기 가입','CASE 그룹','join_year,half_year,customer_count','가입 연도와 반기별 고객 수를 구한다. 1~6월은 1, 7~12월은 2이며 존재하는 그룹만 출력한다.','YEAR(joined_at) AS join_year,CASE WHEN MONTH(joined_at)<=6 THEN 1 ELSE 2 END AS half_year,COUNT(*) AS customer_count','GROUP BY YEAR(joined_at),half_year','join_year,half_year','연도와 반기를 모두 묶어 서로 다른 해가 섞이지 않게 한다.');
b('shop','products','분류별 천원 미만 상품 수','CASE 조건부 개수','category,cheap_count','모든 분류별 가격 1000 미만 상품 수를 구한다. 해당 상품이 없는 분류는 0을 출력한다.','category,SUM(CASE WHEN price<1000 THEN 1 ELSE 0 END) AS cheap_count','GROUP BY category','category','WHERE 대신 CASE를 집계하면 해당 조건이 없는 분류도 남는다.');
b('academy','attempts','강좌별 합격률','NULL 제외 비율','course_id,pass_percent','응시가 있는 강좌별 채점된 응시 중 80점 이상 비율을 백분율로 소수 둘째 자리까지 구한다. 채점된 응시가 없으면 NULL이다.','course_id,ROUND(100.0*SUM(CASE WHEN score>=80 THEN 1 ELSE 0 END)/NULLIF(COUNT(score),0),2) AS pass_percent','GROUP BY course_id','course_id','미채점을 분모에서 제외하고 채점 건수가 0이면 NULL로 나눈다.');
b('academy','attempts','회원별 점수 폭','점수 극값','member_id,score_range','응시한 회원별 채점 점수의 최고점과 최저점 차이를 구한다. 채점이 하나면 0, 전부 미채점이면 NULL이다.','member_id,MAX(score)-MIN(score) AS score_range','GROUP BY member_id','member_id','MIN과 MAX는 NULL을 제외하며 유효값이 전혀 없으면 NULL이다.');
b('academy','enrollments','강좌별 완료율','완료일 COUNT','course_id,enrollment_count,completion_percent','등록이 있는 강좌별 등록 건수와 완료 건수의 백분율을 소수 둘째 자리로 구한다. 재등록도 별도 건수이고 완료가 없으면 0이다.','course_id,COUNT(*) AS enrollment_count,ROUND(100.0*COUNT(completed_at)/COUNT(*),2) AS completion_percent','GROUP BY course_id','course_id','완료일의 NULL 여부를 COUNT로 이용해 완료 건수를 구한다.');
b('academy','enrollments','모두 완료한 등록 회원','COUNT 일치 HAVING','member_id,enrollment_count','등록 이력이 있고 자신의 모든 등록을 완료한 회원과 등록 건수를 구한다. 재등록도 별도로 판단한다.','member_id,COUNT(*) AS enrollment_count','GROUP BY member_id HAVING COUNT(*)=COUNT(completed_at)','member_id','전체 건수와 완료일이 있는 건수가 같으면 미완료가 없다.');
b('academy','enrollments','미완료가 남은 강좌','NULL 개수 차이','course_id,pending_count','미완료 등록이 한 건 이상 있는 강좌와 미완료 건수를 구한다. 재등록은 별도 행이다.','course_id,COUNT(*)-COUNT(completed_at) AS pending_count','GROUP BY course_id HAVING COUNT(*)>COUNT(completed_at)','course_id','전체 행 수에서 NULL이 아닌 완료일 수를 빼면 미완료 수다.');
b('academy','enrollments','강좌별 평균 완료 기간','AVG 날짜 차이','course_id,avg_days','등록이 존재하는 모든 강좌별 완료까지 걸린 평균 일수를 소수 둘째 자리로 구한다. 당일 완료는 0, 미완료는 평균에서 제외하고 완료가 없으면 NULL이다.','course_id,ROUND(AVG(DATEDIFF(completed_at,enrolled_at)),2) AS avg_days','GROUP BY course_id','course_id','날짜 차이의 NULL을 AVG가 제외하므로 미완료를 0으로 바꾸지 않는다.');
b('academy','activity','활동 종류별 평균 길이','평균과 최댓값','kind,average_minutes,max_minutes','활동 종류별 평균 시간과 최대 시간을 구한다. 평균은 소수 둘째 자리, 0분 기록도 포함한다.','kind,ROUND(AVG(duration),2) AS average_minutes,MAX(duration) AS max_minutes','GROUP BY kind','kind','0은 유효한 측정값이므로 평균의 분모에도 포함한다.');
b('academy','activity','회원별 학습일 평균 시간','고유 날짜 분모','member_id,minutes_per_day','study 기록이 있는 회원별 총 study 시간을 서로 다른 study 날짜 수로 나눈 값을 소수 둘째 자리로 구한다. 0분 study 날짜도 분모에 포함한다.','member_id,ROUND(SUM(duration)/COUNT(DISTINCT activity_date),2) AS minutes_per_day',"WHERE kind='study' GROUP BY member_id",'member_id','기록당 평균과 날짜당 평균은 분모가 다르다.');
b('academy','attempts','전체 고유 응시 조합 수','다중 열 COUNT DISTINCT','pair_count','전체 기간에 응시한 서로 다른 회원·강좌 조합 수를 한 행으로 출력한다. 재응시와 미채점 여부는 조합 수에 영향을 주지 않는다.','COUNT(DISTINCT member_id,course_id) AS pair_count','','pair_count','MySQL은 COUNT DISTINCT에 여러 열을 지정해 조합을 셀 수 있다.');
b('academy','attempts','미채점 포함 평균의 차이','COALESCE AVG 비교','graded_average,zero_filled_average','채점된 점수만의 평균과 미채점을 0으로 넣은 전체 평균을 각각 소수 둘째 자리로 출력한다. 전체 응시가 없으면 둘 다 NULL이다.','ROUND(AVG(score),2) AS graded_average,ROUND(AVG(COALESCE(score,0)),2) AS zero_filled_average','','graded_average','AVG 내부에서 NULL을 바꾸면 분모에 미채점 행까지 포함된다.');
b('academy','activity','로그인과 학습을 모두 한 회원','조건부 존재 집계','member_id,login_count,study_count','login과 study 기록이 모두 존재하는 회원과 종류별 기록 수를 구한다. 시간은 조건에 사용하지 않는다.','member_id,SUM(kind=\'login\') AS login_count,SUM(kind=\'study\') AS study_count',"GROUP BY member_id HAVING SUM(kind='login')>0 AND SUM(kind='study')>0",'member_id','한 회원 그룹 안에서 두 조건을 각각 세어 모두 존재하는지 확인한다.');
b('academy','activity','회원별 마지막 학습일','조건부 MAX','member_id,last_study_date','활동 기록이 있는 모든 회원별 마지막 study 날짜를 구한다. login만 있으면 NULL이다.','member_id,MAX(CASE WHEN kind=\'study\' THEN activity_date END) AS last_study_date','GROUP BY member_id','member_id','조건에 맞지 않는 날짜를 NULL로 만들어 MAX에서 제외한다.');
b('academy','attempts','회원별 첫 합격일','조건부 MIN','member_id,first_pass_date','응시한 모든 회원별 최초 80점 이상 응시일을 구한다. 합격이 없으면 NULL이며 미채점은 합격이 아니다.','member_id,MIN(CASE WHEN score>=80 THEN attempted_at END) AS first_pass_date','GROUP BY member_id','member_id','조건부 날짜의 MIN은 사건의 첫 발생일을 구한다.');
b('academy','enrollments','재등록된 회원 강좌','등록 고유 조합','member_id,course_id,enrollment_count,first_enrolled,last_enrolled','동일 강좌에 두 번 이상 등록한 회원·강좌와 등록 횟수, 최초·최종 등록일을 구한다. 완료 여부는 구분하지 않는다.','member_id,course_id,COUNT(*) AS enrollment_count,MIN(enrolled_at) AS first_enrolled,MAX(enrolled_at) AS last_enrolled','GROUP BY member_id,course_id HAVING COUNT(*)>=2','member_id,course_id','재응시와 수강 재등록은 서로 다른 테이블의 사건이다.');
b('academy','courses','분야별 필수 강좌 비중','정수 여부 평균','track,required_percent','분야별 required가 1인 강좌 비율을 백분율로 소수 둘째 자리까지 구한다. required는 0 또는 1이다.','track,ROUND(100.0*AVG(required),2) AS required_percent','GROUP BY track','track','0과 1로 구성된 값의 평균은 1인 행의 비율이다.');
b('academy','courses','분야별 강좌명 길이','문자열 함수 집계','track,shortest_length,longest_length','분야별 강좌명 최소·최대 글자 수를 구한다. 일반 공백도 글자 수에 포함한다.','track,MIN(CHAR_LENGTH(title)) AS shortest_length,MAX(CHAR_LENGTH(title)) AS longest_length','GROUP BY track','track','먼저 각 제목의 글자 수를 구한 뒤 극값을 집계한다.');
b('academy','activity','월별 학습 참여와 시간','다중 집계','activity_month,learner_count,total_minutes','study가 존재하는 연월별 고유 회원 수와 총 학습 시간을 구한다. 연월은 YYYY-MM이고 0분 study도 참여로 센다.','DATE_FORMAT(activity_date,\'%Y-%m\') AS activity_month,COUNT(DISTINCT member_id) AS learner_count,SUM(duration) AS total_minutes',"WHERE kind='study' GROUP BY DATE_FORMAT(activity_date,'%Y-%m')",'activity_month','같은 그룹에서 사람은 고유 개수로, 시간은 모든 행의 합으로 계산한다.');
b('academy','attempts','점수별 응시와 응시자','값별 그룹','score,attempt_count,member_count','채점된 점수별 응시 수와 고유 회원 수를 구한다. 미채점은 제외한다. 높은 점수부터 출력한다.','score,COUNT(*) AS attempt_count,COUNT(DISTINCT member_id) AS member_count','WHERE score IS NOT NULL GROUP BY score','score DESC','동일 점수의 반복 응시는 응시 수를 늘리지만 고유 회원 수는 늘리지 않을 수 있다.');
b('academy','enrollments','완료 월별 완료 수','NULL 필터와 월 집계','completion_month,completed_count','완료가 발생한 연월별 완료 등록 수를 구한다. 미완료는 제외하고 연월은 YYYY-MM이다.','DATE_FORMAT(completed_at,\'%Y-%m\') AS completion_month,COUNT(*) AS completed_count',"WHERE completed_at IS NOT NULL GROUP BY DATE_FORMAT(completed_at,'%Y-%m')",'completion_month','등록일이 아니라 완료일을 기준으로 월을 만들어 집계한다.');
b('academy','attempts','모든 채점이 합격인 회원','MIN과 NULL 정책','member_id,graded_count','채점된 응시가 적어도 하나이고 채점된 모든 점수가 80 이상인 회원과 채점 수를 조회한다. 미채점은 조건 판단에서 제외한다.','member_id,COUNT(score) AS graded_count','GROUP BY member_id HAVING COUNT(score)>0 AND MIN(score)>=80','member_id','최저 채점 점수가 합격선 이상이면 모든 채점 점수가 합격이다.');
b('academy','activity','일별 학습 시간대 분류','CASE 합계 분류','activity_date,total_minutes,day_label','study가 있는 날짜별 총시간과 분류를 구한다. 합계 60분 이상은 집중, 미만은 일반이다.','activity_date,SUM(duration) AS total_minutes,CASE WHEN SUM(duration)>=60 THEN \'집중\' ELSE \'일반\' END AS day_label',"WHERE kind='study' GROUP BY activity_date",'activity_date','행별 시간이 아니라 합계에 CASE를 적용해 날짜를 분류한다.');
b('shop','orders','상태별 주문 활동 기간','집계 날짜 차이','status,span_days','상태별 최초 주문일부터 최종 주문일까지의 날짜 차이를 구한다. 같은 날만 존재하면 0이다.','status,DATEDIFF(MAX(ordered_at),MIN(ordered_at)) AS span_days','GROUP BY status','status','그룹의 날짜 극값을 구한 뒤 두 날짜의 차이를 계산한다.');
b('shop','products','분류별 모든 상품이 천원 이상','전체 만족 HAVING','category,min_price','모든 상품 가격이 1000 이상인 분류와 최저 가격을 조회한다.','category,MIN(price) AS min_price','GROUP BY category HAVING MIN(price)>=1000','category','모든 가격의 하한 조건은 최저 가격으로 검증한다.');
b('shop','order_items','주문별 큰 행 금액 비중','조건부 금액 합계','order_id,large_line_percent','주문별 총금액 중 행 금액이 2000 이상인 상세 행 금액의 비중을 백분율로 소수 둘째 자리까지 구한다. 중복 행을 유지하고 상태를 구분하지 않는다. 주문 총금액이 0이면 NULL이다.','order_id,ROUND(100.0*SUM(CASE WHEN quantity*unit_price>=2000 THEN quantity*unit_price ELSE 0 END)/NULLIF(SUM(quantity*unit_price),0),2) AS large_line_percent','GROUP BY order_id','order_id','금액 기여율은 조건 충족 행 수가 아니라 해당 금액 합계를 분자로 삼는다.');
b('academy','attempts','채점 점수가 두 종류 이상인 강좌','COUNT DISTINCT HAVING','course_id,score_count','서로 다른 채점 점수가 두 종류 이상인 강좌와 점수 종류 수를 조회한다. NULL은 종류 수에서 제외한다.','course_id,COUNT(DISTINCT score) AS score_count','GROUP BY course_id HAVING COUNT(DISTINCT score)>=2','course_id','고유 점수 개수는 응시 건수와 다르며 NULL은 세지 않는다.');
b('academy','activity','요일별 학습량','요일 그룹','weekday_number,total_minutes','study 기록을 월요일 0부터 일요일 6까지 요일별로 묶어 총시간을 구한다. 기록이 없는 요일은 출력하지 않는다.','WEEKDAY(activity_date) AS weekday_number,SUM(duration) AS total_minutes',"WHERE kind='study' GROUP BY WEEKDAY(activity_date)",'weekday_number','전체 기간의 같은 요일을 하나의 그룹으로 합친다.');
b('shop','orders','고객별 주문한 달 수','월 DISTINCT','customer_id,active_months','주문이 있는 고객별 서로 다른 주문 연월 수를 구한다. 모든 상태를 포함하고 같은 달 여러 주문은 한 달로 센다.','customer_id,COUNT(DISTINCT DATE_FORMAT(ordered_at,\'%Y-%m\')) AS active_months','GROUP BY customer_id','customer_id','월 번호만 사용하면 서로 다른 연도의 같은 월이 합쳐지므로 연월을 사용한다.');
b('academy','enrollments','완료 여부별 등록 수','NULL CASE 그룹','completion_state,enrollment_count','전체 등록을 완료일 NULL이면 진행중, 그 외에는 완료로 분류하여 건수를 구한다. 존재하는 분류만 출력한다.','CASE WHEN completed_at IS NULL THEN \'진행중\' ELSE \'완료\' END AS completion_state,COUNT(*) AS enrollment_count','GROUP BY completion_state','completion_state','NULL 검사로 생성한 분류값을 그룹 키로 사용한다.');
b('shop','customers','연월별 가장 빠른 가입일','월별 MIN','join_month,first_joined,customer_count','가입자가 있는 연월별 최초 가입일과 가입자 수를 구한다. 연월은 YYYY-MM이다.','DATE_FORMAT(joined_at,\'%Y-%m\') AS join_month,MIN(joined_at) AS first_joined,COUNT(*) AS customer_count',"GROUP BY DATE_FORMAT(joined_at,'%Y-%m')",'join_month','월별 최소 날짜는 반드시 월 1일인 것이 아니라 실제 첫 가입일이다.');
b('academy','attempts','회원별 합격 강좌 종류 수','조건부 COUNT DISTINCT','member_id,passed_courses','응시가 있는 모든 회원별 한 번이라도 80점 이상을 받은 서로 다른 강좌 수를 구한다. 미채점과 불합격만 있으면 0이다.','member_id,COUNT(DISTINCT CASE WHEN score>=80 THEN course_id END) AS passed_courses','GROUP BY member_id','member_id','조건부로 강좌 번호를 남긴 뒤 고유 개수를 세면 재합격을 중복 집계하지 않는다.');

// 공개 원본 고객 행을 필터·문자열 변환하고, 주문 날짜 극값과 수량 가중 평균을 자바스크립트로 독립 계산한 회귀 표본이다.
problems.find(x=>x.id==='level1_15').expectedRows = [[2,"부산"],[3,null],[5,"대전"],[6,"부산"]];
problems.find(x=>x.id==='level1_17').expectedRows = [[1,"가람(서울)"],[2,"나래(부산)"],[3,"다온(미입력)"],[4,"라온(서울)"],[5,"마루(대전)"],[6,"바다(부산)"]];
problems.find(x=>x.id==='level1_26').expectedRows = [[1,"2024-01"],[2,"2024-01"],[3,"2024-02"],[4,"2023-12"],[5,"2024-03"],[6,"2024-01"]];
problems.find(x=>x.id==='level2_15').expectedRows = [[6,5,83.33]];
problems.find(x=>x.id==='level2_17').expectedRows = [[1,"2024-01-01","2024-02-01"],[2,"2024-01-31","2024-02-01"],[3,"2024-02-01","2024-03-01"],[4,"2024-02-29","2024-02-29"],[6,"2023-12-31","2023-12-31"]];
problems.find(x=>x.id==='level2_19').expectedRows = [[1,1000],[2,500],[3,2750],[4,2000],[5,5000],[6,5000]];
problems.find(x=>x.id==='level1_15').wrongSql = "SELECT customer_id,city FROM customers WHERE city<>'서울' ORDER BY customer_id";
problems.find(x=>x.id==='level1_17').wrongSql = "SELECT customer_id,CONCAT(name,'(',city,')') AS address_label FROM customers ORDER BY customer_id";
problems.find(x=>x.id==='level2_15').wrongSql = "SELECT COUNT(*) AS total_customers,COUNT(city) AS known_cities,ROUND(100.0*COUNT(city)/NULLIF(COUNT(city),0),2) AS known_percent FROM customers ORDER BY total_customers";
problems.find(x=>x.id==='level2_20').wrongSql = "SELECT product_id,COUNT(*) AS order_count FROM order_items GROUP BY product_id ORDER BY product_id";
module.exports = problems;

// 이 파일을 직접 실행하면 개수·식별자·단계 제약과 검증 자료를 확인한다.
if (require.main === module) {
 const assert = require('node:assert/strict');
 assert.equal(problems.length,92);
 assert.equal(new Set(problems.map(x=>x.title)).size,92);
 assert.equal(new Set(problems.map(x=>x.solution)).size,92);
 for (const level of [1,2]) {
  const items=problems.filter(x=>x.level===level);
  assert.deepEqual(items.map(x=>x.id),Array.from({length:46},(_,i)=>`level${level}_${i+15}`));
  assert(items.filter(x=>x.expectedRows).length>=3);
  assert(items.filter(x=>x.wrongSql).length>=2);
 }
 for (const p of problems) {
  assert.equal(p.hints.length,3);
  assert(p.hints[2].includes('/*'));
  assert.equal((p.solution.match(/\bSELECT\b/gi)||[]).length,1);
  assert(!/\bJOIN\b|\bOVER\s*\(|\bWITH\b/i.test(p.solution));
  if(p.level===1)assert(!/\b(COUNT|SUM|AVG|MIN|MAX)\s*\(|GROUP BY/i.test(p.solution));
 }
 console.log('기초 문제 92개 구조 검사 통과');
}
