// 문제별 빈칸 골격이다. 핵심 조건과 계산은 학습자가 채우며 완성 정답은 해설에서만 보여 준다.
module.exports = {
1: [
'SELECT customer_id, name FROM customers WHERE /* 도시 조건 */ ORDER BY /* 고객 번호 */;',
'SELECT product_id, name, price FROM products WHERE price BETWEEN /* 하한 */ AND /* 상한 */ ORDER BY /* 가격과 동점 기준 */;',
'SELECT customer_id, name FROM customers WHERE /* NULL 검사 */ ORDER BY customer_id;',
'SELECT order_id, customer_id FROM orders WHERE /* 결제 상태 */ AND /* 월 시작 이상 */ AND /* 다음 달 시작 미만 */ ORDER BY order_id;',
'SELECT DISTINCT /* 중복 제거할 열 */ FROM products ORDER BY /* 분류 */;',
'SELECT product_id, name, /* 단가 × 수량 */ AS total_price FROM products WHERE /* 분류 조건 */ ORDER BY product_id;',
'SELECT product_id, name FROM products WHERE name LIKE /* 포함 패턴 */ ORDER BY product_id;',
'SELECT course_id, title FROM courses WHERE /* 필수 여부 */ ORDER BY course_id;',
'SELECT enrollment_id, member_id, course_id FROM enrollments WHERE /* 미완료 조건 */ ORDER BY enrollment_id;',
'SELECT attempt_id, member_id, score FROM attempts WHERE /* 점수 하한 */ ORDER BY /* 점수 내림차순, 동점 기준 */;',
'SELECT member_id, name FROM members WHERE region IN (/* 대상 지역 */) ORDER BY member_id;',
'SELECT activity_id, /* 분을 초로 변환 */ AS duration_seconds FROM activity WHERE /* 학습 활동 */ ORDER BY activity_id;',
'SELECT enrollment_id, enrolled_at FROM enrollments ORDER BY /* 등록일, 동점 기준 */ LIMIT /* 최대 행 수 */;',
'SELECT course_id, title FROM courses WHERE title LIKE /* 접두어 패턴 */ ORDER BY course_id;'
],
2: [
'SELECT category, COUNT(*) AS product_count, /* 평균 반올림 */ AS avg_price FROM products GROUP BY /* 분류 */ ORDER BY category;',
'SELECT customer_id, COUNT(*) AS order_count FROM orders WHERE /* 결제 상태 */ GROUP BY customer_id HAVING /* 주문 수 조건 */ ORDER BY order_count DESC, customer_id;',
'SELECT COALESCE(city, /* 대체 문자열 */) AS city_label, /* 고객 수 */ AS customer_count FROM customers GROUP BY city_label ORDER BY city_label;',
'SELECT DATE_FORMAT(ordered_at, /* 월 형식 */) AS month, SUM(/* 결제 조건 */) AS paid_count, SUM(/* 취소 조건 */) AS canceled_count FROM orders GROUP BY month ORDER BY month;',
'SELECT product_id, CASE WHEN /* 저가 */ THEN /* 표시 */ WHEN /* 중가 */ THEN /* 표시 */ ELSE /* 표시 */ END AS price_band FROM products ORDER BY product_id;',
'SELECT customer_id, joined_at FROM customers WHERE joined_at = /* 해당 월 마지막 날 */ ORDER BY customer_id;',
'SELECT order_id, SUM(/* 수량 */) AS total_quantity, SUM(/* 행 금액 */) AS order_amount FROM order_items GROUP BY order_id ORDER BY order_id;',
'SELECT course_id, COUNT(*) AS attempt_count, COUNT(/* 채점된 열 */) AS graded_count, /* 평균 반올림 */ AS avg_score FROM attempts GROUP BY course_id ORDER BY course_id;',
'SELECT activity_date, SUM(/* 시간 */) AS total_minutes FROM activity WHERE /* 학습 활동 */ GROUP BY activity_date ORDER BY activity_date;',
'SELECT member_id, course_id, COUNT(*) AS attempt_count FROM attempts GROUP BY /* 회원·강좌 */ HAVING /* 응시 수 */ ORDER BY member_id, course_id;',
'SELECT enrollment_id, DATEDIFF(/* 완료일 */, /* 등록일 */) AS completion_days FROM enrollments WHERE /* 완료된 행 */ ORDER BY enrollment_id;',
'SELECT member_id, COUNT(DISTINCT /* 날짜 */) AS active_days FROM activity GROUP BY member_id ORDER BY member_id;',
'SELECT CASE WHEN /* 미채점 */ THEN /* 표시 */ WHEN /* 우수 */ THEN /* 표시 */ WHEN /* 보통 */ THEN /* 표시 */ ELSE /* 표시 */ END AS score_band, COUNT(*) AS attempt_count FROM attempts GROUP BY score_band ORDER BY score_band;',
'SELECT member_id, SUM(duration) AS total_minutes FROM activity WHERE /* 학습 활동 */ GROUP BY member_id HAVING /* 합계 조건 */ ORDER BY total_minutes DESC, member_id;'
],
3: [
'SELECT c.customer_id, c.name, COUNT(/* 주문 번호 */) AS paid_count FROM customers c LEFT JOIN orders o ON /* 고객 연결과 결제 조건 */ GROUP BY c.customer_id, c.name ORDER BY c.customer_id;',
'SELECT p.product_id, p.name FROM products p WHERE NOT EXISTS (SELECT 1 FROM order_items i JOIN orders o ON /* 주문 연결 */ WHERE /* 바깥 상품과 결제 조건 */) ORDER BY p.product_id;',
'SELECT /* 도시 표시 */ AS city_label, SUM(/* 구매 당시 금액 */) AS revenue FROM customers c JOIN orders o ON /* 고객 연결 */ JOIN order_items i ON /* 주문 연결 */ WHERE /* 결제 조건 */ GROUP BY city_label ORDER BY revenue DESC, city_label;',
'SELECT p.product_id, p.name, p.price FROM products p WHERE p.price > (SELECT AVG(q.price) FROM products q WHERE /* 같은 분류 */) ORDER BY p.product_id;',
'SELECT c.customer_id, c.name FROM customers c JOIN orders o ON /* 고객 */ JOIN order_items i ON /* 주문 */ JOIN products p ON /* 상품 */ WHERE /* 상태와 대상 분류 */ GROUP BY c.customer_id, c.name HAVING COUNT(DISTINCT /* 분류 */) = /* 필요한 개수 */ ORDER BY c.customer_id;',
'SELECT c.customer_id, c.name, MIN(/* 주문일 */) AS first_paid_at FROM customers c LEFT JOIN orders o ON /* 고객과 결제 조건 */ GROUP BY c.customer_id, c.name ORDER BY c.customer_id;',
'WITH amounts AS (/* paid 주문별 금액, 상품 없는 주문은 0 */) SELECT order_id, order_amount FROM amounts WHERE order_amount > (SELECT /* 주문액 평균 */ FROM amounts) ORDER BY order_amount DESC, order_id;',
'SELECT c.course_id, c.title, COUNT(DISTINCT /* 회원 */) AS member_count FROM courses c LEFT JOIN enrollments e ON /* 강좌 연결 */ GROUP BY c.course_id, c.title ORDER BY c.course_id;',
'SELECT m.member_id, m.name FROM members m WHERE NOT EXISTS (SELECT 1 FROM attempts a WHERE /* 같은 회원이고 채점됨 */) ORDER BY m.member_id;',
'SELECT a.attempt_id, a.course_id, a.score FROM attempts a WHERE a.score > (SELECT AVG(b.score) FROM attempts b WHERE /* 같은 강좌 */) ORDER BY a.attempt_id;',
'SELECT c.track, COUNT(DISTINCT /* 회원 */) AS completed_members FROM courses c JOIN enrollments e ON /* 강좌 연결 */ WHERE /* 완료 조건 */ GROUP BY c.track ORDER BY c.track;',
'SELECT a.attempt_id, a.member_id, a.course_id FROM attempts a WHERE NOT EXISTS (SELECT 1 FROM enrollments e WHERE /* 같은 회원·강좌이고 응시 이전 등록 */) ORDER BY a.attempt_id;',
'WITH best AS (/* 회원·강좌별 채점 최고점 */) SELECT m.member_id, ROUND(AVG(/* 최고점 */), 2) AS avg_best_score FROM members m LEFT JOIN best b ON /* 회원 연결 */ GROUP BY m.member_id ORDER BY m.member_id;',
'SELECT m.member_id, m.name FROM members m WHERE EXISTS (SELECT 1 FROM activity a WHERE /* 같은 회원·가입 당일·학습 활동 */) ORDER BY m.member_id;'
],
4: [
'SELECT customer_id, order_id, ROW_NUMBER() OVER(PARTITION BY /* 고객 */ ORDER BY /* 날짜, 고유 번호 */) AS purchase_number FROM orders WHERE /* paid */ ORDER BY customer_id, purchase_number;',
'WITH ranked AS (SELECT category, product_id, price, DENSE_RANK() OVER(PARTITION BY /* 분류 */ ORDER BY /* 가격 */) AS price_rank FROM products) SELECT * FROM ranked WHERE /* 순위 상한 */ ORDER BY category, price_rank, product_id;',
'SELECT customer_id, order_id, DATEDIFF(ordered_at, LAG(ordered_at) OVER(PARTITION BY /* 고객 */ ORDER BY /* 날짜, 고유 번호 */)) AS gap_days FROM orders WHERE /* paid */ ORDER BY customer_id, ordered_at, order_id;',
'WITH daily AS (/* 날짜별 paid 매출, 상품 없는 주문도 포함 */) SELECT sale_date, revenue, SUM(revenue) OVER(ORDER BY sale_date ROWS /* 누적 프레임 */) AS cumulative_revenue FROM daily ORDER BY sale_date;',
'WITH totals AS (/* 모든 고객별 매출, 미구매는 0 */) SELECT customer_id, revenue, COALESCE(ROUND(/* 개인 매출 / NULLIF(전체 윈도 합계, 0) × 100 */, 2), 0) AS revenue_pct FROM totals ORDER BY customer_id;',
'WITH eligible AS (/* 고객을 보존하며 가입일부터 30일 미만의 paid 주문 연결 */) SELECT e.customer_id, COALESCE(SUM(/* 행 금액 */), 0) AS revenue_30d FROM eligible e LEFT JOIN order_items i ON /* 주문 연결 */ GROUP BY e.customer_id ORDER BY e.customer_id;',
'WITH amounts AS (/* 고객·주문·날짜별 paid 주문액 */) SELECT customer_id, order_id, ROUND(AVG(amount) OVER(PARTITION BY customer_id ORDER BY ordered_at, order_id ROWS BETWEEN /* 직전 행 */ AND CURRENT ROW), 2) AS moving_avg FROM amounts ORDER BY customer_id, ordered_at, order_id;',
'WITH best AS (/* 강좌·회원별 채점 최고점 */) SELECT course_id, member_id, best_score, RANK() OVER(PARTITION BY /* 강좌 */ ORDER BY /* 최고점 */) AS score_rank FROM best ORDER BY course_id, score_rank, member_id;',
'WITH ranked AS (SELECT member_id, course_id, attempt_id, score, ROW_NUMBER() OVER(PARTITION BY /* 회원·강좌 */ ORDER BY /* 최신 날짜와 번호 */) AS rn FROM attempts) SELECT member_id, course_id, attempt_id, score FROM ranked WHERE /* 첫 순번 */ ORDER BY member_id, course_id;',
'SELECT attempt_id, member_id, course_id, score - LAG(score) OVER(PARTITION BY /* 회원·강좌 */ ORDER BY /* 날짜·번호 */) AS score_change FROM attempts WHERE /* 채점된 행 */ ORDER BY member_id, course_id, attempted_at, attempt_id;',
'WITH daily AS (/* 회원·날짜별 학습 시간 */) SELECT member_id, activity_date, SUM(minutes) OVER(PARTITION BY member_id ORDER BY activity_date ROWS /* 누적 프레임 */) AS cumulative_minutes FROM daily ORDER BY member_id, activity_date;',
'WITH ranked AS (/* 채점된 응시에 회원·강좌별 오름차순과 내림차순 순번 부여 */) SELECT member_id, course_id, MAX(CASE WHEN /* 최초 순번 */ THEN score END) AS first_score, MAX(CASE WHEN /* 최신 순번 */ THEN score END) AS last_score FROM ranked GROUP BY member_id, course_id ORDER BY member_id, course_id;',
'WITH best AS (/* 강좌·회원별 채점 최고점 */), ranked AS (SELECT *, ROW_NUMBER() OVER(PARTITION BY course_id ORDER BY /* 최고점과 동점 기준 */) AS rn FROM best) SELECT course_id, member_id, best_score FROM ranked WHERE /* 최대 두 명 */ ORDER BY course_id, best_score DESC, member_id;',
'WITH totals AS (/* 모든 회원별 학습 시간, 비활동은 0 */) SELECT member_id, total_minutes, ROUND(100 * CUME_DIST() OVER(ORDER BY /* 시간만 */), 2) AS cumulative_pct FROM totals ORDER BY total_minutes, member_id;'
],
5: [
'WITH cohort AS (/* 전체 고객의 가입 월과 월 시작일 */), flags AS (/* 다음 달 paid 주문 EXISTS로 retained 생성 */) SELECT cohort_month, COUNT(*) AS customer_count, SUM(retained) AS retained_count, ROUND(/* 유지 비율 */, 2) AS retention_pct FROM flags GROUP BY cohort_month ORDER BY cohort_month;',
'WITH days AS (/* 고객별 paid 날짜 중복 제거 */), numbered AS (/* 고객별 날짜 순번 rn */), islands AS (SELECT *, DATE_SUB(ordered_at, INTERVAL rn DAY) AS grp FROM numbered) SELECT customer_id, MIN(ordered_at) AS start_date, MAX(ordered_at) AS end_date, COUNT(*) AS day_count FROM islands GROUP BY customer_id, grp HAVING /* 연속 길이 */ ORDER BY customer_id, start_date;',
'SELECT c.customer_id, c.name FROM customers c WHERE NOT EXISTS (SELECT 1 FROM products p WHERE /* 필수 분류 */ AND NOT EXISTS (/* 이 고객이 이 상품을 paid로 구매한 행 */)) ORDER BY c.customer_id;',
'WITH RECURSIVE dates AS (/* 출력 시작일 6일 전부터 마지막 날까지 달력 */), daily AS (/* 날짜별 paid 매출 */), rolling AS (SELECT d, SUM(COALESCE(revenue, 0)) OVER(ORDER BY d ROWS BETWEEN /* 앞선 6행 */ AND CURRENT ROW) AS revenue_7d FROM dates LEFT JOIN daily ON /* 날짜 연결 */) SELECT d AS sale_date, revenue_7d FROM rolling WHERE /* 출력 범위 */ ORDER BY sale_date;',
'WITH ranked AS (/* 고객별 paid 주문 순번 */), first_two AS (SELECT customer_id, DATEDIFF(MAX(CASE WHEN /* 두 번째 */ THEN ordered_at END), MAX(CASE WHEN /* 첫 번째 */ THEN ordered_at END)) AS days_to_second FROM ranked GROUP BY customer_id) SELECT c.customer_id, f.days_to_second FROM customers c LEFT JOIN first_two f ON /* 고객 연결 */ ORDER BY c.customer_id;',
'WITH totals AS (/* 월·구매 고객별 매출 */), ranked AS (/* 월별 매출 순번 rn과 고객 수 n */) SELECT month, ROUND(AVG(revenue), 2) AS median_revenue FROM ranked WHERE rn IN (/* 가운데 위치 두 개 */) GROUP BY month ORDER BY month;',
'WITH unique_items AS (/* paid 주문·상품 중복 제거 */) SELECT a.product_id AS product_a, b.product_id AS product_b, COUNT(*) AS order_count FROM unique_items a JOIN unique_items b ON /* 같은 주문, 작은 상품에서 큰 상품으로 */ GROUP BY a.product_id, b.product_id ORDER BY order_count DESC, product_a, product_b;',
'WITH flags AS (/* 전체 회원에 가입 다음 날 학습 EXISTS 표시 */) SELECT joined_at AS cohort_date, COUNT(*) AS member_count, SUM(retained) AS retained_count, ROUND(/* 유지 비율 */, 2) AS retention_pct FROM flags GROUP BY joined_at ORDER BY cohort_date;',
'WITH days AS (/* 회원별 학습 날짜 중복 제거 */), numbered AS (/* 날짜 순번 rn */), lengths AS (/* 날짜-rn으로 그룹별 길이 */), best AS (/* 회원별 최대 길이 */) SELECT m.member_id, COALESCE(b.longest_streak, 0) AS longest_streak FROM members m LEFT JOIN best b ON /* 회원 연결 */ ORDER BY m.member_id;',
'SELECT m.member_id, m.name FROM members m WHERE NOT EXISTS (SELECT 1 FROM courses c WHERE /* 필수 강좌 */ AND NOT EXISTS (/* 이 회원의 이 강좌 완료 기록 */)) ORDER BY m.member_id;',
'WITH daily AS (/* 모든 활동 날짜별로 학습 시간만 합산 */), gaps AS (/* 회원별 LAG 날짜 */), numbered AS (/* 첫 날짜 또는 간격 초과 표시의 누적합으로 session_number */) SELECT member_id, session_number, MIN(activity_date) AS start_date, MAX(activity_date) AS end_date, SUM(minutes) AS total_minutes FROM numbered GROUP BY member_id, session_number ORDER BY member_id, session_number;',
'WITH best AS (/* 강좌·회원별 최고 채점 점수 */), ranked AS (/* 강좌별 순번 rn과 인원 n */), medians AS (/* 가운데 위치의 평균 */) SELECT c.course_id, m.median_best_score FROM courses c LEFT JOIN medians m ON /* 강좌 연결 */ ORDER BY c.course_id;',
'WITH daily AS (/* 회원별 일일 학습 시간 */), running AS (/* 회원별 날짜순 누적 시간 total */), reached AS (SELECT member_id, MIN(activity_date) AS reached_at FROM running WHERE /* 목표 시간 이상 */ GROUP BY member_id) SELECT m.member_id, r.reached_at FROM members m LEFT JOIN reached r ON /* 회원 연결 */ ORDER BY m.member_id;',
'WITH registered AS (/* 회원·등록 강좌 중복 제거 */) SELECT a.member_id AS member_a, b.member_id AS member_b FROM members a JOIN members b ON /* 작은 회원에서 큰 회원으로 */ WHERE EXISTS (/* a의 등록 */) AND NOT EXISTS (/* a에만 있는 강좌 */) AND NOT EXISTS (/* b에만 있는 강좌 */) ORDER BY member_a, member_b;'
]
};
